### PR TITLE
Issue 195

### LINKED ISSUE #195: Improve type handling of pandas functions in the python library
As of v0.24 pandas should now be able to handle integer columns with missing values:
https://pandas.pydata.org/pandas-docs/version/0.24/whatsnew/v0.24.0.html#optional-integer-na-support

Rather than doing the super annoying thing of automatically, and irrevocably, converting an int column to a float when an NaN value is present.  Which, is currently what happens to the DataFrames output by the airr library (eg, `np2_length` is often converted to a float by `airr.load_rearrangement`.)

I think we're going to have to add explicit type declaration to the pandas functions to handle this.

### PR DESCRIPTION
**Pull request by franasa**
fixes #195

### CODE REVIEW

**Comment by franasa** [comment]
hmm It passes the python3 unittest, but 2 fails, will take a look at that tomorrow
```
python -m unittest discover 
-------> tests.test_interface.TestInferface.test_load()
<- 0.024 tests.test_interface.TestInferface.test_load()
.-------> tests.test_interface.TestInferface.test_load_repertoire()
/home/franasa/syncf/PycharmProjects/airr-standards/lang/python/tests/data/bad_repertoire.airr.yaml has repertoire at array position 0 with validation error: MiAIRR field study.study_type is missing
/home/franasa/syncf/PycharmProjects/airr-standards/lang/python/tests/data/bad_repertoire.airr.yaml has repertoire at array position 1 with validation error: MiAIRR field study.study_type is missing
/home/franasa/syncf/PycharmProjects/airr-standards/lang/python/tests/data/bad_repertoire.airr.yaml has repertoire at array position 2 with validation error: MiAIRR field study.study_type is missing
<- 2.976 tests.test_interface.TestInferface.test_load_repertoire()
.-------> tests.test_interface.TestInferface.test_repertoire_template()
<- 0.910 tests.test_interface.TestInferface.test_repertoire_template()
.-------> tests.test_interface.TestInferface.test_validate()
<- 0.001 tests.test_interface.TestInferface.test_validate()
.-------> tests.test_io.TestRearrangementReader.test_validate()
<- 0.005 tests.test_io.TestRearrangementReader.test_validate()
.
----------------------------------------------------------------------
Ran 5 tests in 3.917s

OK
```

**Comment by schristley** [comment]
@franasa The build log has the stack error.

```
ERROR: test_load (tests.test_interface.TestInferface)
360----------------------------------------------------------------------
361Traceback (most recent call last):
362  File "/home/travis/build/airr-community/airr-standards/lang/python/tests/test_interface.py", line 42, in test_load
363    result = airr.load_rearrangement(self.data_good)
364  File "/home/travis/build/airr-community/airr-standards/lang/python/airr/interface.py", line 100, in load_rearrangement
365    df.to_csv(buffer, sep='\t', index=False)  # fill buffer
366  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pandas/core/generic.py", line 3020, in to_csv
367    formatter.save()
368  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 172, in save
369    self._save()
370  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 274, in _save
371    self._save_header()
372  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 242, in _save_header
373    writer.writerow(encoded_labels)
374TypeError: unicode argument expected, got 'str'
375
376
```

**Comment by franasa** [comment]
I realized that earlier today and set up tox for testing.
Turns out that the Python 2.7 csv module [doesn't support](https://docs.python.org/2.7/library/csv.html#module-csv) Unicode input [](https://stackoverflow.com/a/13120279/9578664) so for python 2.7.

If I use io.BytesIO, instead of io.StringIO it works, but there is no solution for both. By the way, is there a reason to keep maintaining support for python 2.7?

**Comment by schristley** [comment]
It's not clear to me what the problem is. We are using the python 2.7 csv module for parsing the rearrangements AIRR TSV without trouble. Is it necessary to have different read code, why not just use the standard RearrangementReader and put the data into a pandas data frame?  I'll admit that I've never used pandas though...

**Comment by franasa** [comment]
The problem is that the issue of this PR (#195), is about using pandas to handle integer columns with missing values (I'm sorry for the uninformative title of this PR).
The simplest solution that I came with, was to use pandas to load the data avoiding the float conversion from the beginning and then converting the `df` back to a file object to load it into the standard `RearrangementReader`. This worked for python 3 with `StringIO` but for python 2.7 I had two find a workaround by importing  `BytesIO as StringIO`.  This solves the issue but that's why put this to review and also why I wanted to ask about the Python 2 support.

**Comment by javh** [comment]
Sorry for the delay. Made some minor tweaks - importantly, increasing the pandas dependency to >= 0.24, which is needed for this change.

Looks ready to merge in to me.

**Review by javh — APPROVED** [review]

**Review by schristley — APPROVED** [review]

**Pull request merged**
