### PR TITLE
Property type redo

### PR DESCRIPTION
**Pull request by bcorrie**
Redo of property_type fixes, with just property_type field but adding detection keywords to suggested strings.

### CODE REVIEW

**Comment by bcorrie** [comment]
Changes as I think we discussed, @bussec I added three possible values, the three former types with a detection method of count, which is I think applicable for our use case. Can you add some other possibilities (and correct mine if in error).

**Review by javh — APPROVED** [review]
I pushed some suggested terms: "rna_umi", "surface_protein_barcode", and "antigen_barcode".

I also set `property_type` as `required` and `nullable: false`.

Yay? Nay? I'm good to merge if those changes are okay.

**Comment by scharch** [comment]
@javh it's a nit, but all 3 are UMIs. Also, I'm not crazy about calling them "barcodes" instead of just `surface_protein` or something. But I don't care enough to make an issue of it if others feel differently.

**Comment by bussec** [comment]
I now added "fluorescence_intensity" as the measured parameter and added `_by_` as a human-readable separator between the property type and the detection method.

**Review by bussec — APPROVED** [review]

**Comment by javh** [comment]
@scharch I agree with you. But, I we decided to make the field a combination of readout and method.

@bussec I'm good with those changes.

**Pull request merged**
