### PR TITLE
Change organism to species

### PR DESCRIPTION
**Pull request by javh**
Per #266, changed `organism` to `species` in Subject.

### CODE REVIEW

**Comment by schristley** [comment]
@javh as I understand this is V2, so we don't merge until after V1.3 is out? or maybe create a V2 branch?

**Comment by javh** [comment]
I labeled with the V2.0 milestone, but I'm not sure that we need to wait... Do you remember when we introduced this field? Can we just make the description language consistent with MiAIRR "Organism" right now and update it to the new MiAIRR language with V2.0?

**Comment by schristley** [comment]
I thought @bussec had said that essentially `organism` was part of the MiAIRR V1, so while it technically wasn't in the AIRR schema yet, it was in the [MiAIRR table](https://github.com/airr-community/airr-standards/blob/v1.0.0/AIRR_Minimal_Standard_Data_Elements.tsv)

**Comment by javh** [comment]
So can we just have this in v1.3:

```
species:
    x-airr:
        name: Organism
```

And then change it in v2.0 to:
```
species:
    x-airr:
        name: Species
```
 Yay? Nay?

**Comment by bussec** [comment]
@javh Yay, this is also my understanding.

@schristley You are right that the `organism` keyword is part of the MiAIRR table, but as it is listed in the "Formats WG" column, so DataRep can could change it.

Or, we just do away with all that "my dance space, your dance space" division, and ask whether this change is a semantic one -- which IMO it is not. Therefore one could argue that it does not change MiAIRR in an incompatible manner and we do the change for field name and key in v1.3.

**Comment by schristley** [comment]
> it does not change MiAIRR in an incompatible manner and we do the change for field name and key in v1.3.

great, let's do it!

**Pull request merged**
