### PR TITLE
Issue #649 Introduced logic to check enums in simple fields.

### PR DESCRIPTION
**Pull request by jday1**
It currently only checks it for array types (Issue #649)

### CODE REVIEW

**Review by javh — APPROVED** [review]
Thanks for the fix. This looks good to me. I'll test and merge.

**Comment by javh** [comment]
Note for @javh: Also add quotes to enums in `AlleleDescription.inference_type`

**Comment by jday1** [comment]
> Thanks for the fix. This looks good to me. I'll test and merge.

Thank you 👍🏼

**Comment by jday1** [comment]
@javh Can I get an update on when you expect this to be merged please? I'm keen to raise further PRs for AIRR enhancements

**Comment by jday1** [comment]
@javh Can I get an update on when you expect this to be merged please? I'm keen to raise further PRs for AIRR enhancements

**Pull request merged**
