### PR TITLE
Clone API initial draft

### PR DESCRIPTION
**Pull request by bcorrie**

### CODE REVIEW

**Comment by bcorrie** [comment]
@schristley any reason we don't merge this into master?

**Review by schristley — APPROVED** [review]
good to merge, we were just waiting for 1.3.1 to be released.

**Comment by bcorrie** [comment]
> good to merge, we were just waiting for 1.3.1 to be released.

I believe 1.3.1 has been tagged and released, correct @javh

**Comment by javh** [comment]
Yep. v1.3.1 has been tagged.

**Pull request merged**
