### PR TITLE
Germline doc

### PR DESCRIPTION
**Pull request by williamdlees**
This closes multiple points raised in [#559]( https://github.com/airr-community/airr-standards/issues/559) and [#562](https://github.com/airr-community/airr-standards/issues/562) - see comment in those threads, and the change notes below. In addition I have raise two new minor issues [#591]( https://github.com/airr-community/airr-standards/issues/591) and [#592]( https://github.com/airr-community/airr-standards/issues/592) so that #559 and #562 can be closed once this pull request is accepted and merged.

### CODE REVIEW

**Comment by williamdlees** [comment]
Also now addresses #556 and #572

**Comment by williamdlees** [comment]
And is also intended to close #590

**Comment by williamdlees** [comment]
germline_description_description doesn't trip off the tongue. Changed the _descriptions to curational_notes, hope that's ok

**Comment by javh** [comment]
I think if the only place we ever plan to use `_notes` is in the germline objects, then I think that's fine.  If we think we might add similar fields outside these objects, maybe we can do a quick informal poll?

Some suffix suggestions:
* `_doc`
* `_notes`
* `_comment`
* `_description`
* None (just `curation`)

Prefix ideas:
* `curational_`
* `curation_`
* None (just `notes`)

I might be a bit overly cautious about future-proofing here, but... thoughts?

**Comment by scharch** [comment]
I kinda like just `comments`
A prefix/suffix seems like overkill unless we think we will also have some other kind of `_notes` (or some other `curation_`, I suppose)

**Comment by bussec** [comment]
@williamdlees I updated the sections of the Schema that were changed by #524, #564 and #603, but excluded the (non-MHC) germline objects. The merge to master should now work again, the only problem is that the R test is failing again (@javh, any ideas)?

**Comment by javh** [comment]
I just checked the R package locally and I'm not seeing the same `Duplicate map key: 'InformationProvider'` error from `yaml::yaml.load_file`.  I'll have to fight with it.

**Comment by javh** [comment]
The R check failure was due to merging against master generation a duplicate copy of the `InformationProvider` object in the specs, which is why the error wasn't present locally. I'm not sure how that happened, but I blame the force-push creating an improper merge conflict resolve.

Seems fixed now.

**Comment by bussec** [comment]
@javh Thanks for all the troubleshooting! I really hate to say it but you fixed the consistency check, but now the merge conflicts are back :cry: I did so testing locally and the order of the commits seems to matter, so let me check whether squashing solves the issue...

**Comment by javh** [comment]
Haha. Okay, well.. Let's hope. We may have to clean it up post-merge or something.  I think we just have the "notes" fields to deal with for this PR, yes?

**Comment by bussec** [comment]
Finally! It did not require squashing, a rebase to the current `master` was sufficient. So know we got consistency checks, commit history and the ability to actually merge this :tada: Everyone who is on a local repo, please remember to update this branch before making any new commits.

**Review by bussec — APPROVED** [review]

**Comment by bussec** [comment]
@javh 

> I think if the only place we ever plan to use _notes is in the germline objects, then I think that's fine. [...]  Maybe we can do a quick informal poll?

In general I hope that we will not need additional comments fields like this, as they might be abused as dumps for information that should go into other existing fields. However, I recognize that when representing/exchanging GLDB data there is a valid use case for comments on the curation process. So it is ok to make an exception here, but IMO we do not need to agree on a common suffix.

**Comment by bussec** [comment]
@javh Is there anything more we need to discuss regarding the `curational_notes`?

**Comment by javh** [comment]
Not really, I think you're right that it's unlikely to have a broader use case, so we just need to pick something.  Any objections to just `curation`?

**Comment by williamdlees** [comment]
No objection from me.

**Comment by williamdlees** [comment]
This would be ok with me. The description already says ‘curational notes’ so it doesn’t really matter if it’s in the name. In my use case at least.

**Pull request merged**
