### PR TITLE
Test R-CMD-check using GitHub Actions

### PR DESCRIPTION
**Pull request by javh**
A test PR using GitHub actions.

### CODE REVIEW

**Comment by javh** [comment]
Check runs in 3:43 using the rocker/verse image.  ~2:30 of that is `R CMD check` itself, which isn't going to get any faster. 

~50 sec is setting up the container - not sure yet if that can be reduced via caching

**Review by bussec — APPROVED** [review]
LGTM, thanks!

**Comment by javh** [comment]
Coolness. I'll add the python tests and see if I can use a smaller container before merging.

**Comment by javh** [comment]
First draft of GitHub actions for the schema consistency checks, R package, and python package are now in this PR. They are in separate configs in the `.github/workflows` directory.

I also added a condition to whether the tests will be run for the R and python packages that requires a change in either the GitHub actions config or `lang/R` / `lang/python` as appropriate. Which should save a lot of time, because then we don't need to run the R tests every time we change the schema.  It's a bit annoying to test though, because the workflow is skipped, so I can disable it for now if we want.

**Pull request merged**
