### PR TITLE
Add species information to `cell_subset` and `locus` fields

### LINKED ISSUE #137: How to indicate xenografted or transgenic animals
MiAIRR currently assumes that all entries in a record pertain to the same `species`, which is defined in data set 1. As `species` will be `required` (#96) and restricted by a species taxonomy (most likely NCBITAXON, #97) we need a mechanism to describe subjects that cannot be clearly assigned to a single species. Two examples of such a subject would be:

* Animals containing complete human immunoglobulin loci as transgenes. Note that it is not possible to unambiguously infer the species from `target_locus` as the gene symbol does often not contain this information. Therefore the sequence information could be wrongly interpreted as host sequences.

* Chimeric animals that have been grafted with human bone marrow (and potentially other tissues). Here also additional fields like `cell_subset` would be affected.

One solution would be to introduce a "species prefix" for the fields involved. However, as this changes MiAIRR, it a slightly bigger decision.

### PR DESCRIPTION
**Pull request by bussec**
fixes #137 

Also addresses #139 point 1

### CODE REVIEW

**Comment by bussec** [comment]
Yes. I think this should be a general principle that the same field on lower levels overwrites the field on higher levels. The questions that come into mind:
1. Where should this be documented
2. Would it be smart to use high level field name as suffix (probably: yes)

**Comment by schristley** [comment]
> Where should this be documented?

Adding to the `description` should be sufficient.

**Comment by bussec** [comment]
`description` added, are we good to go?

**Comment by schristley** [comment]
@bussec looks good, so we are sticking with `subject.organism` and not changing it?

**Comment by bussec** [comment]
See my post in #266, we are changing the MiAIRR name, but it won't happen before early next year, as this is a major version step. Would you like to combine those changes or merge this one here for now and see how the decision turns out for the other one?

**Comment by schristley** [comment]
Okay then, let's merge this now and leave the changes considered MiAIRR V2 for later.

**Comment by bussec** [comment]
The `locus_species` part has now been moved into #614.

**Pull request merged**
