### PR TITLE
Switch to [vdjc]_call

### PR DESCRIPTION
**Pull request by laserson**
Fixes issue with `_call` in #5.

### CODE REVIEW

**Comment by schristley** [comment]
@laserson Can this be redirected to `development` branch? New dev flow is locking master merges except for releases. I changed the base branch to `development`, but it's now showing a ton of commits besides yours?

**Comment by laserson** [comment]
No problem, but would this dev flow be up for discussion?  It appears the dev branch is already very far behind the master branch somehow, and this is one of the disadvantages of that approach.  I'd personally advocate for all development on master, and putting tags on release commits.  If things need to be patched in earlier releases, you branch off of that commit.  (I think this is how most Apache projects are run.)

**Comment by schristley** [comment]
Yeah, things were getting confusing as some people where committing to master and some work is being done on development. We merged master into development so that should bring development forward. This will get all cleaned up with the release this week and we can all be on the same dev flow going forward.

**Comment by laserson** [comment]
Ok, this is off `development` now.

**Pull request merged**
