### PR TITLE
operator documentation

### LINKED ISSUE #298: Functionality of is operator
In looking at the implementation of the ADC API "is" operator in the ADC API on iReceptor, we have stumbled on an issue... I think this is probably an @schristley question 8-)

In the document, the "is" operator checks to see if a field is "missing". The question is, what is the definition of missing?

This was touched on here: https://github.com/airr-community/airr-standards/issues/239#issuecomment-531391095

The ADC API test for this is here (https://github.com/airr-community/adc-api-tests/blob/master/repertoire/pass-is-op.json):
```
{
  "filters": {
    "op":"is",
    "content": {
      "field":"sample.cell_number"
    }
  }
}
```
This returns a list of repertoires where the sample.cell_number field is missing. My understanding from #239 is missing in this case means that the field **is not in the repository** or the field **is in the repository** but is **null** for a given repertoire.

Put a different way, the above query would return the repertoire where "cell_number" == null

```{"repertoire_id":"1", ... , "sample" : { "cell_number":null, ... }, ... }```

I wanted to confirm, from my understanding of #239, that this interpretation is correct?

### PR DESCRIPTION
**Pull request by schristley**
fixes #298 

Also changed operator examples to be JSON, and `organism.id` is a string.

### CODE REVIEW

**Comment by bcorrie** [comment]
@schristley in Pull #322 I added a section on operations on arrays. I think something like this is still needed, no, as we don't capture that information in this pull request... I think combined perhaps they do the trick.

It also occurred to me that maybe we should add `array` to the `Value Data Types` column of the operator documentation

It also occurred to me that if we don't add `array` to the `in` and `exclude` operators then the weird semantics of `exclude` on arrays don't need to be explained... Do you think it is the end of the world if the spec does not allow `in` and `exclude` on fields that are arrays???

Thoughts?

**Comment by schristley** [comment]
> I think something like this is still needed...

Yes, I agree, still needed.

> It also occurred to me that maybe we should add array to the Value Data Types column of the operator documentation

Ok, that sounds good.

> It also occurred to me that if we don't add array to the in and exclude operators then the weird semantics of exclude on arrays don't need to be explained... Do you think it is the end of the world if the spec does not allow in and exclude on fields that are arrays???

I don't think we can get away from it. When you are doing a query on `sample.tissue`, even though the `tissue` field is a base data type, `sample` is an array, so technically the query is being performed on an array. That is, if the repertoire has multiple samples in the array, doing a query on `sample.tissue` will operate like how you documented.

**Comment by bcorrie** [comment]
> > It also occurred to me that maybe we should add array to the Value Data Types column of the operator documentation
> 
> Ok, that sounds good.

You or me... 8-) I can add this if you haven't already...

**Comment by schristley** [comment]
> You or me... 8-) I can add this if you haven't already...

I can stick it in this PR real quick as it's modifying that table. I wanted to merge this as #298 has been decided, so we can check another one off the list!

**Comment by schristley** [comment]
@bcorrie added array for `in` and `exclude` in table. Good to merge?

**Pull request merged**
