### PR TITLE
Update nullable fields, add additional fields to AlleleDescription

### PR DESCRIPTION
**Pull request by williamdlees**
In germline objects, remove all nullable: false entries and add x-airr: qualifiers instead.

- Move aligned sequence to SequenceDelineationV and change co-ordinates in SequenceDelineationV to be against the unaligned sequence rather than the aligned sequence. This makes AlleleDescription delineation-agnostic and removes reliance on an alignment for the co-ordinates
- Add fields to AlleleDescription for Allele Similarity Cluster designation

### CODE REVIEW

**Comment by williamdlees** [comment]
fixed UndocumentedAllele name

**Comment by williamdlees** [comment]
Withdrawn while I work on updating the test data

**Review by bussec — COMMENTED** [review]
@williamdlees please find my comments below:

* The following properties should IMO be `essential`:
    - `RearrangedSequence.derivation`
    - `RearrangedSequence.observation_type`
    - `AlleleDescription.species`
    - `GermlineSet.species`
    - `MHCGenotype.mhc_class`
* `AlleleDescription.coding_sequence.description`: Is it intended to refer to IMGT Ontology here?
* `AlleleDescription.allele_similarity_cluster*` needs more description and an example. The description should clarify whether "similarity" is different from "identical" and if yes to which degree.
* Could `Genotype.receptor_genotype_set_id` be renamed to `genotype_set_id` to avoid confusion with the `receptor_*` properties of the `Receptor` object.
* MHCGenotype.mhc_alleles is an array-of-objects (and not an array-of-refs)


* As a note: According to [wiki](https://en.wiktionary.org/wiki/derivation#Noun) the term "derivation" does not refer to the source of the process (or its at least ambigous).

**Comment by javh** [comment]
From the call:
* `species`, `mhc_class`, and `observation_type` as essential makes sense.
* Check with IARC on `RearrangedSequence.derivation`.
* `coding_sequence.description` can we be more explicit here? Can we use the following as a guide? https://docs.airr-community.org/en/stable/miairr/specification_miairr_ncbi.html.
* Can't change `Genotype.receptor_genotype_set_id` in a minor release. Maybe v1.5.
* Replacement of object (`MHCGenotype.mhc_alleles`) with reference should be fine for v1.4.2.

**Comment by williamdlees** [comment]
- `species`, `mhc_class`, and `observation_type` marked as essential.
- No strong views from IARC regarding RearrangedSequence.derivation (the name waa reviewed and agreed by IARC some years ago)> Possible alternatives should they be required could be `derived_from`, `sample_source`, `nucleic_acid_class.`.
- `coding_sequence.description`changed to `nucleotide sequence of the core coding region, i.e. the coding region of a D-, J- or C- gene, or the coding region of a V-gene excluding the leader`. I think this is pretty specific now.
- object (MHCGenotype.mhc_alleles) replaced with reference to a new top-level object MHCAllele.

**Comment by bcorrie** [comment]
Re-structuring of MHCGenotype and Genotype objects to include object references rather than embedded objects looks like it is correct to me.

**Review by bcorrie — APPROVED** [review]
MHCGenotype and Genotype object restructuring (no more embedded objects) looks like it is correct to me.

**Comment by javh** [comment]
From the call:
* Add additional description and clarification for `AlleleDescription.allele_similarity_cluster*` in the Germline documentation (see above comment from @bussec).

**Pull request merged**
