### PR TITLE
Start of autobuild TSV and re-enable consistency checks

### PR DESCRIPTION
**Pull request by javh**
1. Added autobuild of Rearrangements and Alignment TSVs to docs build.
2. Added `specs/miairr.yaml` with MiAIRR content of old TSV.
3. Made formats consistency check function (no refactor - just made it run.)
4. Moved consistency checks to `/tests`

Probably can't get back to this task for a bit (#29), so just want to merge what exists now for cleaner history.

### CODE REVIEW

**Comment by schristley** [comment]
I'm okay with the PR, but do we need `miairr.yaml`? Any advantage to doing that versus putting custom attributes `x-miairr-set`, etc., in `definitions.yaml`? It just seems like we traded one file for another, just different format.

**Comment by bussec** [comment]
@schristley see our comments [here](https://github.com/airr-community/airr-standards/issues/29#issuecomment-381345810). I don't have any strong opinion about one or files, but would prefer having everything in YAML (instead YAML+TSV).

**Comment by javh** [comment]
So something like this?

**definitions.yaml**

```
Study:
   discriminator: AIRR
   type: object
   properties:
      study_id:
         type: string
         description: Unique ID assigned by study registry
         x-miairr-set: 1
	 x-miairr-subset: study
	 x-miairr-name: Study
	 x-miairr-format: free text
	 x-miairr-example: PRJNA001
```

I was originally thinking more like this:

**miairr.yaml:**

```
Study:
    set: 1, study
    format: free text
    example: PRJNA001   
```

**definitions.yaml:**

```
Study:
   discriminator: AIRR
   type: object
   properties:
      study_id:
         type: string
         description: Unique ID assigned by study registry
         x-miairr: Study
```

So the `miairr.yaml` file is setup with the MiAIRR standard as the top level and the formats spec contains a cross-reference.

The first is easier to maintain, but the second retains MiAIRR independence, which is probably both good and bad. Either way (or an entirely different way) will work to autogenerate the tsv.

**Comment by schristley** [comment]
> So something like this?

Yeah, but now that I've re-read the discussion, I'm good with a separate `miairr.yaml` file. The object schemas in `definitions.yaml` are actually preliminary and weren't approved by MiAIRR, so letting them have their own file retains their independence. I'll note that `miairr.yaml` is not OpenAPI compliant for schema/field definitions though, so we might change it later if that ends up being needed.

**Comment by javh** [comment]
Yeah, we can assess the format of `miairr.yaml` later. Just want something in place for now.

**Pull request merged**
