### PR TITLE
Added data_processing_files

### PR DESCRIPTION
**Pull request by bcorrie**
Added a data_processing_files field, non MiAIRR, optional as per the discussion in #276

### CODE REVIEW

**Comment by javh** [comment]
@bcorrie, do you mind if I throw the changes for #268 into this PR as well? They're semi-related.

**Comment by bcorrie** [comment]
> this should be an array.

Change made - waiting on Travis checks to pass...

**Comment by bcorrie** [comment]
> > this should be an array.
> 
> Change made - waiting on Travis checks to pass...

Hmmm, @schristley @javh it looks like there are some new Travis checks that have been added... Can someone fill me in on what needs to be updated for these...

**Comment by javh** [comment]
The tests for the python reference library are failing:

```
======================================================================
FAIL: test_load_repertoire (tests.test_interface.TestInferface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/airr-community/airr-standards/lang/python/tests/test_interface.py", line 78, in test_load_repertoire
    data = airr.load_repertoire(self.rep_good, validate=True)
KeyError: 'data_processing_files'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/airr-community/airr-standards/lang/python/tests/test_interface.py", line 80, in test_load_repertoire
    self.assertTrue(False, 'load_repertoire(): good data failed')
AssertionError: False is not true : load_repertoire(): good data failed
======================================================================
FAIL: test_repertoire_template (tests.test_interface.TestInferface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/airr-community/airr-standards/lang/python/tests/test_interface.py", line 52, in test_repertoire_template
    result = airr.schema.RepertoireSchema.validate_object(rep)
KeyError: 'data_processing_files'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/airr-community/airr-standards/lang/python/tests/test_interface.py", line 55, in test_repertoire_template
    self.assertTrue(False, 'repertoire_template(): repertoire template failed validation')
AssertionError: False is not true : repertoire_template(): repertoire template failed validation
```

**Comment by bcorrie** [comment]
> The tests for the python reference library are failing:

Are these new tests or I have I never made a change to the spec that caused these tests to fail (which I find odd) 8-)

**Comment by javh** [comment]
> Are these new tests or I have I never made a change to the spec that caused these tests to fail (which I find odd) 8-)

There haven't been any commits to `test_interface.py` in 4 months... At least in main.

**Comment by schristley** [comment]
@bcorrie For handling arrays with simple data type items, the validate code can simply check that each entry (row) in the array is the correct type. I cut/paste code from lines 381-388 which check basic types. I guess maybe the try/catch is needed...

```
   elif spec['items'].get('type') == 'boolean':
      try:
         self.to_bool(row, validate=True)
      except ValidationError as e:
         raise ValidationError('array field %s has %s' %(f, e))

and so on for integer and number (string?)
```

There should still be an `else` to capture unhandled types like "object".

```
                    else:
                        raise ValidationError('Internal error: array field %s in schema not handled by validation. File a bug report.' %(full_field))
```

**Comment by bcorrie** [comment]
> @bcorrie For handling arrays with simple data type items, the validate code can simply check that each entry (row) in the array is the correct type. I cut/paste code from lines 381-388 which check basic types. I guess maybe the try/catch is needed...
> 
> ```
>    elif spec['items'].get('type') == 'boolean':
>       try:
>          self.to_bool(row, validate=True)
>       except ValidationError as e:
>          raise ValidationError('array field %s has %s' %(f, e))
> 
> and so on for integer and number (string?)
> ```

So what is the validation for string??? to_bool etc assume a string and convert to bool. So at this point are we assuming that this is a string so no validation is required?

**Comment by bcorrie** [comment]
@schristley I changed the array processing of the validation code, can you have a review of that. It looks like it works...

**Comment by schristley** [comment]
> So what is the validation for string??? to_bool etc assume a string and convert to bool. So at this point are we assuming that this is a string so no validation is required?

Um, Yes?? I was thinking the same thing when I wrote that... I guess the old code (rearrangement validation) is assuming you are reading from a TSV file and thus yes the fields come in as strings, and get converted to appropriate types.

With repertoire metadata as json, we should probably explicitly check for string type.

And now that I think about it, we probably shouldn't be using the `to_` functions to convert, because we don't convert repertoire metadata when reading/writing, thus we should just check the type directly:

```
   elif spec['items'].get('type') == 'boolean':
      if not isinstance(row, boolean):
         raise ValidationError(...
```

**Comment by bcorrie** [comment]
Do you want to merge this in to master and create a separate issue for that fix?

**Comment by schristley** [comment]
> Do you want to merge this in to master and create a separate issue for that fix?

nah, I committed the needed changes to this PR.

**Comment by javh** [comment]
From the call:
* Can this be deferred to v2.0 with an overall of DataProcessing?
* If not, good to merge.

**Pull request merged**
