### PR TITLE
Change read_length to be two integer fields for paired reads

### LINKED ISSUE #279: Should read_length be an array of integers?
Currently read_length is specified as a string of the format [300,300]

Computationally, this isn't very useful. I want to do a search for all read_lengths > 300 and there is no effective way to do this in the sense that the data is a string and could have odd formatting issues...

I suppose this might be a good time to confirm that there should be one field for this, with an array of either one element or two elements depending on if it was paired-read sequencing???

### PR DESCRIPTION
**Pull request by bcorrie**
Fixes #279

### CODE REVIEW

**Comment by bcorrie** [comment]
Can someone have a look at the wording I used in the description....

@bussec this is a MiAIRR term, do you have any concerns about this change... This change implies a MiAIRR set change for the field.

**Comment by bcorrie** [comment]
@bussec left the fields to be in MiAIRR set 3, although they are now in the Schema block `RawSequenceData` where all of the other fields are MiAIRR set 4. But I don't think we want this change to induce an incompatibility. If we want to change the MiAIRR set then we can do that in v2???

Otherwise I think this is ready to merge...

**Comment by schristley** [comment]
We'll have to see how the MiAIRR TSV comes out in the docs. I think the [code](https://github.com/airr-community/airr-standards/blob/6acb7f2936ffafa141369e984229288518701bfc/docs/conf.py#L301) implicitly relies on the fact that the order of definitions in the schema is in set order (1, 2, 3, ...) so these fields may show up in an odd place.

**Comment by bussec** [comment]
Fine with me. Regarding the `set`: Strictly spoken, the addition of the other `set: 4` fields already broke compatibility as they are new requirements that were not present in v1.0. However `set: 4` is kind of an strange place for MiAIRR anyhow (as it is just the raw data), so in reality nothing depends on this.

The remaining problem with moving `read_length` to Set 4 is the NCBI mapping, as this needs to be updated. I am fine with doing this after we merge this in, but it will be another to-do for v1.3.

**Comment by bussec** [comment]
Created the issue to fix the docs: #330

**Pull request merged**
