### PR TITLE
Issue 475 and 433

### LINKED ISSUE #475: read_rearrangement in the R package is vulnerable to confusion about column types from readr::read_tsv
I have a file that is giving the following warning from `airr:read_rearrangement`, which is from `readr::read_tsv`:

```
Warning: 84610 parsing failures.
row    col             expected               actual
7570   d_call_10x      1/0/T/F/TRUE/FALSE     IGHD1-1
7591   vjl_group       1/0/T/F/TRUE/FALSE     G21 
```
Leading to all `NA` values in those columns.  Using `guess_max=10000` with `readr::read_tsv` avoids the error.
Those aren't AIRR columns, but we should still be loading them honestly somehow. Maybe by adding a `guess_max` argument to pass through to `read_tsv` or by defaulting unrecognized fields to type `character`.

### PR DESCRIPTION
**Pull request by ustervbo**
Add argument to `airr::read_airr()` to define the type of non-schema columns, with character as default.

Fitting unit test is added. Test data created on the fly from toy_data.tsv

Closes #475 and #433

### CODE REVIEW

**Comment by scharch** [comment]
For #433 this should be done for the python library, as well. I might have some time next week...

**Comment by javh** [comment]
Thanks, @ustervbo!  I made some minor change: shorted the argument name, extra docs, added the change to the news, and stuck you in the author list.

Can you confirm you want to be in the package author list and confirm the email address I put is correct, please?

**Review by javh — APPROVED** [review]

**Comment by schristley** [comment]
It looks like these types are very R-specific. Should we be more generic and use OpenAPI types? I like the idea in #433 of passing in an OpenAPI field structure. Is there any reason not to do that?

**Comment by javh** [comment]
> It looks like these types are very R-specific. Should we be more generic and use OpenAPI types? I like the idea in #433 of passing in an OpenAPI field structure. Is there any reason not to do that?

Meaning:
string -> character
number -> double
integer -> integer
boolean -> logical

**Comment by javh** [comment]
From the call:
* Make the type name change from @schristley and merge in.

**Pull request merged**
