### PR TITLE
Updates to the Schema release notes

### PR DESCRIPTION
**Pull request by javh**
I was about to tag the v1.3 release when I noticed our schema release notes weren't current.  I went through the diff here and made a bunch of edits:
https://github.com/airr-community/airr-standards/compare/v1.2.1..master

I'm going to need some help though. Not sure if I got everything relevant, if my descriptions are correct, etc.

### CODE REVIEW

**Comment by javh** [comment]
https://docs.airr-community.org/en/v1.3-news/standards/news.html

**Comment by javh** [comment]
Do we want to include release notes for the R and python libraries in the schema news? They have their own release notes sections:

https://docs.airr-community.org/en/v1.3-news/packages/airr-python/news.html
https://docs.airr-community.org/en/v1.3-news/packages/airr-R/news.html

**Comment by schristley** [comment]
How about we make the news file more prominent in the docs? Add to Getting Started? or AIRR Standards? When I got to the docs top page, it isn't clear where to click to read the news.

**Comment by schristley** [comment]
> Do we want to include release notes for the R and python libraries in the schema news? They have their own release notes sections:

That's a good point. I was thinking of this as a top-level news versus just for the schema. I think it's fine to have them separate but we should be able to find them all in at least one place together on the docs site.

**Comment by javh** [comment]
> How about we make the news file more prominent in the docs? Add to Getting Started? or AIRR Standards? When I got to the docs top page, it isn't clear where to click to read the news.

We could have a Release Notes item between Getting Started and AIRR Standards. Then link to or include all individual release note pages for the schema, python library, R library, and ADC API

**Comment by javh** [comment]
I'm done fiddling with it. I made a top level Release Notes section, moved some stuff around, and converted the schema bullet points to numbers in an effort to fix the formatting while preserving the comments.

**Pull request merged**
