### PR TITLE
extensions property

### LINKED ISSUE #555: how to know if a repository supports an ADC extension?
I was thinking we could add an `extensions` array into the info object, which might be an easy way to programmatically determine if a repository supports an ADC extension. While we only have one extension now with the async API, CRWG has been considering adding the stats API, and we might have more in the future. It could be a simple keyword array like this:

```
extensions:
  - asynchronous
  - statistics
```

### PR DESCRIPTION
**Pull request by schristley**
closes #555

### CODE REVIEW

**Comment by schristley** [comment]
@bcorrie good to merge?

**Comment by bcorrie** [comment]
@schristley the addition looks good, but it doesn't look like there is any documentation on the asynchronous endpoint. Am I missing them somewhere? It looks like the async spec is kind of an orphan (from a docs perspective at least).

If there aren't any docs there probably should be (an adc_api_extensions.rst), and we probably need a paragraph in the overview page (rather than the bullet point) that describes what extensions are (maybe a "Extensions" section above the "Authentication" section on the overview page) and point the Extensions docs???

**Comment by schristley** [comment]
> @schristley the addition looks good, but it doesn't look like there is any documentation on the asynchronous endpoint. Am I missing them somewhere? It looks like the async spec is kind of an orphan (from a docs perspective at least).

Do you mean this #545 ? Yes, it still needs to be written.

**Comment by bcorrie** [comment]
Ah yes - if that is in the works then I think good to merge this.

**Review by bcorrie — APPROVED** [review]

**Pull request merged**
