### PR TITLE
R vignettes

### PR DESCRIPTION
**Pull request by ssnn-airr**
Added vignette draft.

### CODE REVIEW

**Comment by ssnn-airr** [comment]
I know what this problem is:

`Quitting from lines 94-101 (AIRR-standards.Rmd) 
Error: processing vignette 'AIRR-standards.Rmd' failed with diagnostics:
'' does not exist in current working directory ('/tmp/RtmpHiBSvd/Rbuild288d539cb64/airr/vignettes').
Execution halted`

working on fix.

**Comment by ssnn-airr** [comment]
Seriously??? AAAAhhh!!

**Comment by javh** [comment]
The problem is that the `tests` directory doesn't exist inside the built package. So, you'll probably have to move `/tests/data-tests` to `/inst/data-tests` and then reference it in the tests via `system.file("data-tests/file.tsv", package="airr")`

**Comment by javh** [comment]
Ah, or maybe we just need to build with `--install-tests` to get system.file("/tests/data-tests") to work. That might be better, if it works.

**Comment by ssnn-airr** [comment]
I suspect `system.file("data-tests/file.tsv", package="airr")` works if the packages is installed.

**Comment by javh** [comment]
Yeah, I got all mixed up. Sorry. Forgot we weren't running `R CMD install` during travis... One sec. Fixing.

**Comment by ssnn-airr** [comment]
No worries. I can't wait for the day I experience the joy of a problem free pull request. I am still getting used to this.

**Pull request merged**
