### PR TITLE
First pass at finalizing the Rearrangement fields.

### PR DESCRIPTION
**Pull request by javh**
1. Commented out metadata file generation in the formats python library.
2. Updated Rearrangement fields per discussion in issue #85. There were some conflicts in the opinions, so I just made arbitrary decisions in those cases where preferences weren't universal. I think I got everything? Except `mutated_invariant` - I think it's best to skip that for now, because it seems to be contentious and I don't think I've ever actually used that field for anything anyway.
3. I made some small improvements to the field descriptions for clarity, but we need to take a pass over the text for all of them more thoroughly once finalized.
4. Changed the MiAIRR `JUNCTION` mapping in the consistency check TSV from `junction_nt` to `junction`.
5. Updated the toy data in the python library with new column names.

### CODE REVIEW

**Comment by schristley** [comment]
Looks good!

1. This technically changes the MiAIRR spec with TSV data element name change (`junction_nt` -> `junction`). I think we are okay with this, but is the `junction_nt` name being used anywhere? For example, has any data been submitted to GenBank with `junction_nt`?

2. How are we defining the coordinate fields in relationship to the sequence/alignment fields and `rev_comp`? Should tools automatically assume that a coordinate can be used directly on the sequence, or do they need to check `rev_comp` and reverse complement before applying the coordinates?

**Comment by javh** [comment]
1. The official name for submission to GenBank/TLS is `JUNCTION`. `junction_nt` was specific to the Rearrangement format and hasn't been used elsewhere, to my knowledge. (That's part of why I changed it.)
2. Good question. I'm inclined to go with IgBLAST's approach from @jianye00: "all output data (i.e., alignment coordinates, nucleotide sequence, translated protein sequence, etc) are based on the reversed/complemented sequence of the original read." Ie, check `rev_comp` and reverse complement before applying the coordinates.

**Comment by javh** [comment]
Planning to merge this Thursday, if there are no further comments.

**Comment by BusseChristian** [comment]
Fine with me.

**Pull request merged**
