### PR TITLE
initial airr-js package

### PR DESCRIPTION
**Pull request by schristley**
- [x] finish I/O routines
- [x] add tests
- [x] API documentation?
- [ ] npm account, publish, update release procedures

### CODE REVIEW

**Comment by javh** [comment]
@schristley , we're wrapping up for a release right now. Is this something that will be ready to go or should we push it to v2.0?

**Comment by schristley** [comment]
@javh Note that schema fixes like #697 are needed for validation to work.

**Comment by javh** [comment]
Ah, okay. So close, but maybe not quite there yet. Hrm. Maybe v2 then? Even though it is close.

**Comment by javh** [comment]
@schristley Is this close to complete?

**Comment by schristley** [comment]
> @schristley Is this close to complete?

It is. I'll work on the last bits this month and get it merged.

**Pull request merged**
