### PR TITLE
Clone api

### PR DESCRIPTION
**Pull request by bcorrie**
Pull request to discuss addition of the Clone API

### CODE REVIEW

**Comment by bcorrie** [comment]
@schristley I notice a possible problem with the /rearrangement/{sequence_id} and /repertoire/{repertoire_id} endpoints in that the response object is the same as the /rearrangement and /repertoire endpoints. I don't think this is correct, as it contains a `Facets` JSON block that is not possible to get with the {_id} endpoints. I think this should be fixed, not sure if we should fix it through this pull request or not.

**Comment by schristley** [comment]
The /clone/{clone_id} endpoint implies that `clone_id` has a uniqueness scope similar to repertoire_id.

**Comment by schristley** [comment]
> notice a possible problem...

For the /clone endpoint, the response also suggests that `Facet:` and `Clone:` can be returned in the same response, which shouldn't happen, will that be fixed too?

**Comment by bcorrie** [comment]
> The /clone/{clone_id} endpoint implies that `clone_id` has a uniqueness scope similar to repertoire_id.

Based on discussions today at DataRep, I would think of it more like sequence_id for /rearrangements. Unique within a repository...

**Comment by bcorrie** [comment]
> > notice a possible problem...
> 
> For the /clone endpoint, the response also allows for `Facet:` and `Clone:` to be returned in the same response, which shouldn't happen, will that be fixed too?

Seems like one would want to perform the same types of counting operations that Facets provides for Clones, just like Rearrangements, so I would think that would be fine... That is why I left it in...

**Comment by schristley** [comment]
> > The /clone/{clone_id} endpoint implies that `clone_id` has a uniqueness scope similar to repertoire_id.
> 
> Based on discussions today at DataRep, I would think of it more like sequence_id for /rearrangements. Unique within a repository...

Yes, that too is similar to repertoire_id. You made this recent [comment](https://github.com/airr-community/airr-standards/issues/421#issuecomment-651372216) so I wasn't sure of your intent.

> the clone_id is unique within a Repertoire, or perhaps more precisely within a repertoire_id/data_processing_id pair

**Comment by schristley** [comment]
> > > notice a possible problem...
> > 
> > 
> > For the /clone endpoint, the response also allows for `Facet:` and `Clone:` to be returned in the same response, which shouldn't happen, will that be fixed too?
> 
> Seems like one would want to perform the same types of counting operations that Facets provides for Clones, just like Rearrangements, so I would think that would be fine... That is why I left it in...

I agree, though the size of the clone data is on the order of rearrangements, so we might want to consider similar restrictions. However, that wasn't what I meant. `clone_response` allows a response to contain both `Facet` and `Clone` like this:

```
{
  Facet: [ stuff snipped ],
  Clone: [ stuff snipped ]
}
```

Is that valid? I was assuming not, so asking if that will be fixed too?

**Comment by bcorrie** [comment]
> I agree, though the size of the clone data is on the order of rearrangements, so we might want to consider similar restrictions. However, that wasn't what I meant. `clone_response` allows a response to contain both `Facet` and `Clone` like this:
> 
> ```
> {
>   Facet: [ stuff snipped ],
>   Clone: [ stuff snipped ]
> }
> ```
> 
> Is that valid? I was assuming not, so asking if that will be fixed too?

Is it possible to specify that with YAML? I think both are valid responses, so they need to be included, they just shouldn't appear together? I think that needs to be specified at the documentation level, not the spec level doesn't it?

I modeled this response on the /rearrangement response, so unless I made a mistake with the copy I think the /rearrangement and /repertoire endpoints have the same problem, no? I think the issue is probably addressed in the documentation for them - but we don't have any Clone documentation yet 8-)

**Comment by schristley** [comment]
> Is it possible to specify that with YAML?

It seems so, TACC pointed out to me that openapi V3 has the `OneOf` [keyword](http://spec.openapis.org/oas/v3.0.3#properties). I don't think it was available in V2 though.

**Comment by schristley** [comment]
@bcorrie This looks fine to me, want to merge it?

**Pull request merged**
