### PR TITLE
info object

### LINKED ISSUE #147: Info object in airr-schema.yaml?
I'm thinking of adding a simple Info object into the yaml file that has a description, version, URL, etc. Essentially stuff that was in the [original schema](https://github.com/airr-community/airr-formats/blob/master/specs/rearrangements.yaml) from long ago.

I realize this becomes another version and etc. to maintain but I think it might be useful for tools that use the schema but don't use a reference library (or can access the underlying git info)

### PR DESCRIPTION
**Pull request by schristley**
fixes #147 

My proposal for an Info object in the schema. Not sure if the list of schema is needed or not, but I added as a way to be more specific versus just relying upon whatever is in the file. There should be an API mechanism to get this object.

### CODE REVIEW

**Comment by laserson** [comment]
What's the purpose of this object?

**Comment by schristley** [comment]
The [original schema](https://github.com/airr-community/airr-formats/blob/master/specs/rearrangements.yaml) had some simple info like a description, version, url, etc., that I think is useful.

**Comment by javh** [comment]
Looks fine to me. Except, I think the schema list is unnecessary and a potential cause of errors (by failing to replicate the object set correctly). This information already exists in the schema file as the set of member objects.

**Comment by laserson** [comment]
Ditto. I don't think the schema stuff needs to be there. But otherwise I think it's good.

**Comment by schristley** [comment]
Not sure what you mean by "member objects", but I see by studying the code more that a `Schema` object is for a specific definition, not for the whole schema file. So I think you need to need know the names of the definitions beforehand, unless I'm misunderstanding something.

I removed the schema list, and made some minor code changes to prevent loading "Info" as a definition and make info a variable e.g. `airr.schema.RearrangementSchema.info`

**Comment by javh** [comment]
> Not sure what you mean by "member objects", but I see by studying the code more that a Schema object is for a specific definition, not for the whole schema file. So I think you need to need know the names of the definitions beforehand, unless I'm misunderstanding something.

Sorry, by "member objects" I mean the other top level items in the yaml file (the individual schema). Needing to know the schema name before loading it is just a quirk of how we've implemented it. We can change that, though I don't know that we should. You can get the list of schema from just reading the entire yaml file.

**Comment by javh** [comment]
Oh, and do we need `info.description` for the python API? We could just populate `Schema.version` and `Schema.url`. If `info` is just a blob of unknown data, then it'll be easier to change what it contains, but also less obvious what it does contain... So I don't have a strong opinion. 

We should do the same thing in R though.

**Comment by schristley** [comment]
> Needing to know the schema name before loading it is just a quirk of how we've implemented it. We can change that, though I don't know that we should. You can get the list of schema from just reading the entire yaml file.

That's fine. That schema list was a way to give them, but I don't it's that important, the definitions are gonna be pretty much set in stone after awhile.

**Comment by schristley** [comment]
> We should do the same thing in R though.

I'm working on the R code now. I'm not sure how to test though, I've never try to use the R library yet. Does travis run some tests for R?

**Comment by schristley** [comment]
> Oh, and do we need info.description for the python API? We could just populate Schema.version and Schema.url. If info is just a blob of unknown data, then it'll be easier to change what it contains, but also less obvious what it does contain... So I don't have a strong opinion.

That information needs to be in the schema file itself, not just properties coded in the python Schema object, if that is what you are asking. For the very reason you mention before, people may directly just read the schema file (e.g. that is exactly what I'll be doing for some javascript UI code).

**Comment by javh** [comment]
There are Travis tests. The R package has unit tests (using testthat), which you can run manually using: ``devtools::test()``.

More details here:
http://r-pkgs.had.co.nz/tests.html

**Comment by javh** [comment]
> That information needs to be in the schema file itself, not just properties coded in the python Schema object, if that is what you are asking. For the very reason you mention before, people may directly just read the schema file (e.g. that is exactly what I'll be doing for some javascript UI code).

No, I meant we could instead assign `Schema.version` and `Schema.url` directly from the `Info` section of the yaml file, instead of having `Schema.info.version` and `Schema.info.url`. And probably skip `info.description` because it's a level above and therefore not really correct information. There could be a 'Rearrangement.description' entry in the yaml file though, that we could populate that from, if we think it's necessary.

**Comment by schristley** [comment]
> No, I meant we could instead assign Schema.version and Schema.url directly from the Info section of the yaml file, instead of having Schema.info.version and Schema.info.url.

I see. Yeah that's a good point. The OpenApi has an [Info schema definition](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#infoObject) and I think we should follow it. Though I see now I'm missing the required `title` field...

**Comment by javh** [comment]
> The OpenApi has an Info schema definition and I think we should follow it. Though I see now I'm missing the required title field...

Sounds good to me. Then we can rely on those fields being permanent.

**Comment by schristley** [comment]
@javh I'm hacking my way through the R stuff, I went to the lang/R directory and did these commands:

```
R -e 'install.packages(c("devtools", "roxygen2", "testthat"))'
R -e 'devtools::install_deps(dep=T)'
R -e 'devtools::document()

Updating airr documentation
Loading airr
Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  : 
  Dependency package readr not available.
```

I needed to install `readr` and `yaml` packages before `document()` gave me the real error I'm seeing in the travis build. Should those packages be added as dependencies?

**Comment by javh** [comment]
> I needed to install readr and yaml packages before document() gave me the real error I'm seeing in the travis build. Should those packages be added as dependencies?

No, the are already listed as dependencies. See the `Depends` and `Imports` sections of the `DESCRIPTION` file. Those commands should be fine. (The first two shouldn't even be necessary in the Travis build, but R in Travis isn't behaving well.)

The error you're getting is due to a missing slot spec in the class definition. You need:

```
setClass("Schema", 
         slots=c(required="character",
                 optional="character",
                 properties="list",
                 info="list"))
```

(And to specify the type in the roxygen `@param` field, but that won't cause an error. It's just incomplete docs.)

**Comment by schristley** [comment]
green for go!

**Comment by schristley** [comment]
@javh Did you already review? I'd like to merge if no objections.

**Comment by javh** [comment]
Oh, sure, I thought we were swapping doing the swap from stuff like `Schema.info.version` to `Schema.version`? Doesn't need to be now if you want to merge.

**Comment by schristley** [comment]
> Oh, sure, I thought we were doing the swap from stuff like Schema.info.version to Schema.version? 

We can do that specifically for `version` if you want, but there are a bunch of fields defined by the OpenAPI spec for the Info object, and it also allows [Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#specificationExtensions), i.e. custom attributes that start with `x-` so it seems easier to just leave it all under `Schema.info`

**Comment by javh** [comment]
Gotcha. Nevermind then. Sorry, I would've pushed approve last week if we hadn't gotten our wires crossed.

**Pull request merged**
