### PR TITLE
autogenerate MiAIRR TSV from yaml schema

### LINKED ISSUE #29: Auto generate definitions.yaml from TSV?
Hi All,

I was wondering if it might make sense to auto generate the definitions.yaml file from the MiAIRR TSV file rather than have a consistency check???

There are a couple of reasons for this:

1) They won't ever be out of sync (assuming the generation is done automatically). Probably worth having the Travis job still to ensure this and catch bugs in the conversion 8-)

2) The definitions would be more complete. Currently the definitions.yaml file is very minimal with name and type. The YAML object spec accepts descriptions and examples for fields in the definition. The TSV file has both field descriptions and examples. It would be nice if these could be added to the definitions.yaml file. I was going to do it manually but thought that is a lot of mundane work and will make it even harder to keep the two consistent. The driver for this is that our API uses the definitions.yaml file. But the API description is pretty bare bones as it has no descriptions or examples. It would be nice if the definitions.yaml file had this information.

3) When using the MiAIRR definitions in a swagger API spec like we are, we need definition in multiple forms. For swagger API responses, we need swagger objects. For API parameters, we need a different YAML structure, essentially a list of single parameters and their types, descriptions, and examples. Similar to #2 above, it would be nice if we could automatically generate a parameters.yaml file from the TSV.

I am happy to work on the code snippets to do this... The consistency check that we have now is a good starting point.

Thoughts?

I can create a branch for this development...

Brian

### LINKED ISSUE #255: Not clear how "Content format" is stored in the yaml file
Hi all, as my first contribution I made this simple script to create a .tsv file from the airr-schema.yaml. It is not clear to me how the "Content format" column from AIRR_Minimal_Standard_Data_Elements.tsv was created, can anyone give me a hint?
I am also looking forward to any feedback (I hope I'm not breaking anything)

### PR DESCRIPTION
**Pull request by schristley**
fixes #29
fixes #255

### CODE REVIEW

**Comment by schristley** [comment]
@javh @bussec Are we okay with the format of the TSV changing slightly?

**Comment by schristley** [comment]
Also, while the file is autogenerated, do we also want to actually commit it to the repository? Just in case any outside sources are pointing to it?  We could probably add a Travis consistency check to see if the files (committed version versus the one generated by the docs) are different. I suppose the bad thing about that is that is may force devs to build the docs to get a new version to commit.

**Comment by javh** [comment]
I don't think we should commit it. People can get persistent link by linking to the docs site.

**Comment by javh** [comment]
Yeah, I don't think we need the check anymore.

Do we want to render the TSV as a table in the docs somewhere, like we did for the schema fields? Eg: http://docs.airr-community.org/en/latest/datarep/rearrangements.html#fields

**Comment by schristley** [comment]
> render the TSV as a table in the docs

Yeah that would be nice actually, I like being able to preview it without importing into excel

**Comment by javh** [comment]
Okay, here's something not-very-good just to get us started:
http://docs.airr-community.org/en/issue-255_2/miairr/data_elements.html#miairr-elements

The page needs more words and better formatting. We should probably rename the columns too.

Pinging @franasa and @bussec.

**Comment by javh** [comment]
Do we need both the `MiAIRR field designation` and `AIRR Schema field name` columns?

**Comment by bcorrie** [comment]
> Do we need both the `MiAIRR field designation` and `AIRR Schema field name` columns?

I think the AIRR Schema field name is probably important, as it gives a precise mapping to the spec.

I would lean toward having the field designation as well, as a "short name" for the field???

**Comment by javh** [comment]
Yeah, I agree we should have the schema field name.  

`MiAIRR field designation` contains the designations used in the MiAIRR manuscript. It now seems redundant to me, but maybe we need to keep it for clarity? Not sure if it fosters or hinders clarity to have two "fields names" in the table.

If we did drop it, then I think we would also have to remake the figure here:
http://docs.airr-community.org/en/issue-255_2/miairr/introduction_miairr.html

**Comment by schristley** [comment]
> Do we need both the MiAIRR field designation and AIRR Schema field name columns?

Yes, they serve different purposes, one is the human-readable form and the other is the computable form. The first will be useful for showing in UIs and such.

It's worthwhile to change `MiAIRR field designation` to something else...

**Comment by schristley** [comment]
@javh is it possible to change the table into a multi-row table, that is, each record uses multiple rows instead of on a single row. The `MiAIRR content definition` and `Field value example` could be put on their own rows, this would provide them with more space for the long content, and maybe allow the whole table to fit better width-wise.

**Comment by javh** [comment]
> @javh is it possible to change the table into a multi-row table, that is, each record uses multiple rows instead of on a single row.

I don't know. I'll look into it. Not as part of the `csv-table` directive, but we there _might_ be a way to set multirow columns with the `tabularcolumns` directive.

**Comment by bussec** [comment]
What is the motivation behind changing `MiAIRR field desgination`? I am not generally opposed to it, just would like to understand the issue. Is there anything else that needs to be done from the MiniStd side?

**Comment by javh** [comment]
> What is the motivation behind changing `MiAIRR field designation`? I am not generally opposed to it, just would like to understand the issue. Is there anything else that needs to be done from the MiniStd side?

It's just a cosmetic concern. It makes the table wider and it contains information that is already in `MiAIRR content definition` and `AIRR Schema field name` (I assume the MiAIRR field names predates the full AIRR schema field names). So the table looks kind of cluttered on the docs site. But if we need it, we will figure out how to smoosh it.

No, I don't think there's anything needed from MiAIRR.

**Comment by schristley** [comment]
@javh There is something called [Grid Tables](https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/lists_tables.html#grid-tables) which supports column/row spanning. Though I'm not sure if that's available in our theme?

**Comment by bussec** [comment]
@javh I agree that the `MiAIRR field designation` is redundant to the combination of the two other fields. However, these are the designations used in the MiAIRR1.0 manuscript, hence we have to kepp them for now. We can discuss deprecation for MiAIRR2.0.

**Comment by javh** [comment]
Sounds good. In the interest of getting this merged in, I pushed a commit with shorter names for the columns.  The table is still a bit ugly, but I'm not sure how to clean it up at the moment. Maybe we can address that separately?

(@schristley, I don't think we can use grid tables, not because of the theme, but because we are loading the table from a tsv.)

**Comment by bcorrie** [comment]
@javh I notice that there is a "study_description" field in the spec and there is no study_description in the documentation table... I also notice in the spec that that there are no x-airr fields for study_description (is this why it is not generated). I am pretty sure study_description should be included in the MiAIRR spec, no??? @bussec is that correct?

**Comment by bussec** [comment]
@bcorrie this field (`study_description`) does not exist in MiAIRR, which only know `study_type`. See #163 for more background. Currently I do not consider the free text description to be minimal, but plese let me know if you think otherwise.

**Comment by bcorrie** [comment]
@bussec no problem, was just a bit confused as I had forgotten that decision... One question - study_description as a field used to be in MiAIRR v1.2.1. It is now not in MiAIRR but it is still in the spec. Is there some way we can denote this so tools can track this compatibility change? It isn't a deprecated field in the spec sense (since it is still in the spec) but it is deprecated in the MiAIRR sense as it is no longer in MiAIRR...

**Comment by javh** [comment]
> One question - study_description as a field used to be in MiAIRR v1.2.1.

Do you mean in the sense that it had `x-miairr: true` in the AIRR schema file at v1.2.1 of the schema?

MiAIRR "owns" the major version number, so technically I think everything in MiAIRR is supposed to be locked in to what was in v1.0.0 until we bump the repo release to v2.0.0. If my understanding is correct, then the discrepancy between the `x-miairr` tags between v1.2.1 and the tip is just a mistake.

**Comment by schristley** [comment]
> If my understanding is correct, then the discrepancy between the x-miairr tags between v1.2.1 and the tip is just a mistake in v1.2.1.

It's a little more convoluted than that. The semantics of the field changed. `study_description` was MiAIRR but it described a "type" versus being a "description", to fix that semantic, the field was renamed to `study_type`, that's the MiAIRR field. Then `study_description` was re-introduced to be a "description" field but it isn't MiAIRR.

Technically, MiAIRR standard didn't change, it always required a "study type" but the field name in the schema used to store that information was changed. I suppose this should go into the Changelog...

**Comment by javh** [comment]
Ah, okay. Thanks, @schristley.

**Pull request merged**
