### PR TITLE
Initial merged Sphinx docs

### PR DESCRIPTION
**Pull request by laserson**
This PR switches to a more traditional sphinx build (using RST). It also autogenerates the formats field tables upon building, so we don't have to check-in the built docs anymore.  It's still rough, but once this is merged in, we can work to continuously improve the docs.

cc @javh @schristley @ahmadchan @BusseChristian

### CODE REVIEW

**Comment by laserson** [comment]
The build failed bc I had to add a dummy `Alignment` object into `definitions.yaml`.  I'd prefer to fix this *after* merging this in.

**Comment by schristley** [comment]
I think if you add the discriminator keyword to the Alignment object, the checks should pass.

`discriminator: AIRR`

**Comment by laserson** [comment]
Good call @schristley

**Comment by laserson** [comment]
We Haven is it

On Dec 12, 2017 17:45, "Scott Christley" <notifications@github.com> wrote:

Merged #65 <https://github.com/airr-community/airr-standards/pull/65>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/airr-community/airr-standards/pull/65#event-1384588318>,
or mute the thread

**Comment by BusseChristian** [comment]
Does anyone want to resuscitate this branch? Otherwise I will delete it.

**Pull request merged**
