### PR TITLE
add unit ontologies

### LINKED ISSUE #420: time unit for `collection_time_point_relative`
The MiAIRR property `collection_time_point_relative` is a time value (the current example for it is _14 d_). 
Should a **`collection_time_point_unit`** ontology property be defined as it was done for age with `age_unit` in https://github.com/airr-community/airr-standards/issues/192?.

### PR DESCRIPTION
**Pull request by franasa**
fixes #420

### CODE REVIEW

**Comment by schristley** [comment]
Thanks @franasa please also update the schema version in `Info` at the top of the file from 1.3 to 1.4.

@javh We might want to hold off merging in case we want to release a 1.3.1, just to avoid dealing with multiple release branches?

**Comment by javh** [comment]
> We might want to hold off merging in case we want to release a 1.3.1, just to avoid dealing with multiple release branches?

That seems wise. Maybe we can bump the R package task to v1.4 and and then v1.3.1 is an easy doc and definition clarification release.

**Comment by bcorrie** [comment]
@franasa I made some changes so the Travis checks passed, I think this is ready to be merged... Let me know if you want me to pull the trigger on the merge.

**Comment by franasa** [comment]
looking good. thanks! @bcorrie @schristley

**Pull request merged**
