### PR TITLE
schema for AIRR data file

### PR DESCRIPTION
**Pull request by schristley**
An explicit schema for an AIRR data(metadata) file. This is an extension of the file format for Repertoire metadata (which just has the `Info` and `Repertoire` keys) to include the additional AIRR objects. The format continues the earlier design where the output from the ADC API exactly matches the file format. Also an `Info` object schema is provided. This was previously only in the ADC API spec.

`Rearrangement` implies rearrangement data in JSON (versus TSV). We might want to consider how to extend this format for #426 so that the data file can refer to TSV files.

This shows how `DataProcessing` can be a "top-level" object.

### CODE REVIEW

**Comment by schristley** [comment]
When we define a schema for `RepertoireGroup` or `RepertoireSet`, that can be added in the format as an additional key.

**Comment by bcorrie** [comment]
This kind of feels to me like it should be in a different .yaml file and refer to the other object definitions in airr_schema.yaml like the ADC API schema does???

This seems to need a airr_fileformat.yaml or something like that - do we want to combine the two?

**Comment by bcorrie** [comment]
There is an Info and an InfoObject - can we unify these two?

**Comment by bcorrie** [comment]
Also, if I understand correctly, this would subsume our AIRR Repertoire file format definition, which is essentially:
```
DataFile:
    discriminator: AIRR
    type: object
    properties:
        Info:
            $ref: '#/InfoObject'
        Repertoire:
            type: array
            description: List of Repertoire metadata
            items:
              $ref: '#/Repertoire'
```
Did I get that correct?

**Comment by schristley** [comment]
> Also, if I understand correctly, this would subsume our AIRR Repertoire file format definition, which is essentially:

Yes, exactly. Our current definition is only described in the documentation, so this makes it formal and machine readable.

**Comment by schristley** [comment]
> There is an Info and an InfoObject - can we unify these two?

They are different things. InfoObject is a schema definition (class) while Info is a concrete instance of InfoObject, in this case the Info for the airr-schema.yaml file. Normally, I would have labeled InfoObject as just Info but that obviously conflicts...

**Comment by scharch** [comment]
Do we really want to create a schema where eeeeeverything is in one file? Where you potentially have to load alllll the `Rearrangement`s to access the metadata? Even for JSON, I think I would prefer a manifest that allows more flexibility with putting different pieces in different places...

**Comment by schristley** [comment]
> Do we really want to create a schema where eeeeeverything is in one file?

I don't mean to imply this with the schema, though maybe I suggest with my comment. Each of the keys are optional, so a data file can be any mixture of data. I don't expect all data to be in one file, but in a set of these files. These files might naturally correspond to output from queries to the different endpoints (repertoire, clone, cell) in the ADC API.

> Even for JSON, I think I would prefer a manifest that allows more flexibility with putting different pieces in different places...

Yep, this schema is just one part, a manifest needs to say what files are grouped together.

Rearrangements are a special case because we already have a TSV file format, and I expect rearrangement data to be in their own files. I mostly have the key there for completeness, so that it matches the `/rearrangement` end point in the ADC API. The same may be true for other objects like clones, if we define a TSV format for them.

**Review by scharch — APPROVED** [review]

**Comment by javh** [comment]
From the call:
Should we add a "Custom" property that holds a list of non-AIRR files? The intent being to allow users to bundle random files in manifest/directory/tarball with the AIRR schema-defined files.

**Comment by bcorrie** [comment]
Here is an example download "manifest" from the iReceptor Gateway:

```
* Summary *
Total: 21 sequences
covid-19-2.tsv: 0 sequences (1.8 KB)
covid-19-1.tsv: 7 sequences (4.1 KB)
covid-19-3.tsv: 4 sequences (3.3 KB)
covid-19-4.tsv: 10 sequences (5.6 KB)


* Metadata filters *
None

* Sequence filters *
Junction/CDR3 AA: CATSEGQGSQPQHF

* Source *
/sequences?query_id=8653
Downloaded by bcorrie on Nov 16, 2020 at 20:34 UTC
```
The ZIP file contains the following files:
```
covid-19-1.tsv
covid-19-2.tsv
covid-19-3.tsv
covid-19-4.tsv
covid-19-1-metadata.json
covid-19-2-metadata.json
covid-19-3-metadata.json
covid-19-4-metadata.json
```

**Comment by bcorrie** [comment]
A more complicated download manifest whose query hits all of the repositories:

```
* Summary *
Total: 70 sequences
ireceptor-public-archive-3.tsv: 7 sequences (4.9 KB)
ireceptor-public-archive-2.tsv: 41 sequences (17.2 KB)
ireceptor-public-archive-4.tsv: 0 sequences (1.8 KB)
airr-covid-19-2.tsv: 0 sequences (1.8 KB)
ireceptor-public-archive-5.tsv: 8 sequences (5.5 KB)
airr-covid-19-1.tsv: 0 sequences (1.8 KB)
airr-covid-19-4.tsv: 2 sequences (2.6 KB)
airr-covid-19-3.tsv: 1 sequences (2.2 KB)
ireceptor-public-archive-1.tsv: 0 sequences (1.8 KB)
vdjserver.tsv: 11 sequences (20.2 KB)


* Metadata filters *
None

* Sequence filters *
Junction/CDR3 AA: CSARRGLAGSDTQYF

* Source *
/sequences?query_id=24427
Downloaded by bcorrie on Nov 16, 2020 at 20:44 UTC
```

**Comment by bcorrie** [comment]
I have fundamental question about this file format and its intent. This schema addition (either in the same or a different file) seems to be defining a rigorous file format for any combination of object in the AIRR schema. This is important...

My question is, is this really a Manifest file as implied by the title in #426 and the description in that issue. I think the intent of the manifest file that @schristley is talking about is more of a true manifest file (https://en.wikipedia.org/wiki/Manifest_file) while the YAML description we have is a file format for objects in the schema. I actually think we need both...

For example, I don't think the YAML schema in this pull request would be able to describe the set of files that would be included in an iReceptor download. In terms of a manifest file, don't we want something that formalizes a grouping of data files that captures a set of data that is to be used for a specific purpose. In the iReceptor download case the manifest would describe the set of files that correspond to the results of the potentially complicated query that the user issued through the Gateway.

I think that is more along the lines of what we are talking about when we say manifest file, no?

**Comment by schristley** [comment]
> I actually think we need both...

That's correct, we need both. The manifest should be described with a schema. In the last meeting, we discussed if we should put it in `Info` or maybe it should be it's own `Manifest` object. I'm leaning towards the latter.

**Pull request merged**
