### PR TITLE
clone schema Olmsted validation

### PR DESCRIPTION
**Pull request by eharkins**
Working on validating clones using the AIRR clones and trees schema in Olmsted!

It seems like the way null/None values are allowed in the AIRR schema at the moment is via [the `x-airr.nullable` field](https://github.com/eharkins/airr-standards/blob/b109492b17971ed8001a911131bf5e77772602f5/specs/airr-schema.yaml#L114). Since in Olmsted, I am just loading in the Clones portion of the yaml schema into my python script and validating directly from there with the [jsonschema](https://python-jsonschema.readthedocs.io/en/stable/) package, I can't make use of that field to allow null values for certain attributes.

The two ways I can think of to allow null values instead of using `x-airr.nullable` are:
1. The way I have done in this pull request
2. [Extending the validator](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-with-additional-types) to take null in place of any field of type string in the schema. 

Some examples of things I would like to leave as null:
- `Clone.repertoire_id`, since we aren't yet adopting the AIRR Repertoire object / concept in Olmsted; because this is a required field in the AIRR schema here, I understand if you don't want to allow null values for it.
- `Clone.seed_id`: the [description](https://github.com/airr-community/airr-standards/compare/master...eharkins:olmsted_clones_validation?expand=1#diff-7d67e9142fe90cadc6c257313a117f65R2660) says 
> null if no seed

so it seems at least worth adding the `x-airr.nullable` for you own validation purposes.

Thanks!

### CODE REVIEW

**Comment by eharkins** [comment]
p.s. I think [the fact that I've put quotes around `null` means it will be compatible in Swagger](https://github.com/pipermerriam/flex/issues/91#issuecomment-164507549)

**Comment by javh** [comment]
I think we have some issues to resolve with `x-airr.nullable` (see #297), particularly at levels above Rearrangement (sample meta data and such).

Every field in the Rearrangement schema is nullable, despite not having an `x-airr.nullable = True` attribute. I think we should apply the same assumption here, as Clone/Tree are "downstream" of Rearrangement, while we sort out the issues with the `x-airr` attributes.

**Comment by schristley** [comment]
OpenAPI V3 has a specific `nullable` attribute, but V2 does not. That's why we have `x-airr: nullable`. Once we move to V3, we can use the `nullable` attribute and get rid of `x-airr: nullable`

**Comment by eharkins** [comment]
@javh 
>  I think we should apply the same assumption here, as Clone/Tree are "downstream" of Rearrangement, while we sort out the issues with the x-airr attributes.

Sounds good. How do you allow for this when validating if the `null` type isn't explicitly included in those fields in the schema?

**Comment by javh** [comment]
> Sounds good. How do you allow for this when validating if the `null` type isn't explicitly included in those fields in the schema?

In the reference python/R API packages we treat an empty string as None/NA.

**Comment by eharkins** [comment]
Ah ok. I am using the [generic jsonschema python package](https://python-jsonschema.readthedocs.io/en/stable/validate/) since specific tools for validating AIRR Clones schema in [python don't seem to exist yet](https://github.com/airr-community/airr-standards/tree/master/lang/python).

 [It seems like you are not directly using jsonschema for validation](https://github.com/airr-community/airr-standards/pull/251#issuecomment-550401412) in those API packages, so for now I will probably stick with [allowing strings to be null](https://github.com/matsengrp/olmsted/commit/80b6ec75c7bd919868f9c945f0b447ade638c913) when validating the AIRR spec using jsonschema.

**Comment by javh** [comment]
I'm not familiar with jsonschema, so I'm not sure how to get around the null issue with it. 

But, I don't think we want to add multiple type declarations to fields. That sounds like it would break a lot of things. And ultimately, the nullability mechanism will be in a separate property of some kind (`x-airr: nullable` or `nullable`, as @schristley describes).

If you can't just save empty strings to these fields, can you just exclude them from your output?  `repertoire_id` is currently set in `required`, but removing it from `required` seems a simpler change.  The json/yaml/tsv should still be valid if an optional (non-required) field isn't present (that's what makes them optional).

**Comment by scharch** [comment]
> specific tools for validating AIRR Clones schema in [python don't seem to exist yet](https://github.com/airr-community/airr-standards/tree/master/lang/python).

Actually, that's a good point. We will clearly want this at some point fairly soon, but it seems like it might be too late for 1.3...




> I can't recall exactly what we decided about `repertoire_id` in the clones/tree discussion before, but given recent conversations, it's possible that `repertoire_id` is in the top level `required` just because it had `x-airr: required = true`.

@javh hmmm maybe, but I think we probably want to hold off on that change until #297 is resolved, yes? And in that case, it probably *shouldn't* be `nullable`?

**Comment by javh** [comment]
> @javh hmmm maybe, but I think we probably want to hold off on that change until #297 is resolved, yes? And in that case, it probably _shouldn't_ be `nullable`?

Maybe? The safest bet is probably to just copy `Clone.repertoire_id` unmodified from Rearrangement, which is absent from the top level `required` with:

```
x-airr:
    miairr: false
    required: true
    nullable: true
    adc-api-optional: false
```

Then change it when/if the `x-airr` tags are changed in the rest of the schema after #297 is sorted.

**Comment by eharkins** [comment]
Not having `Clone.repertoire_id` be required sounds good to me.

**Comment by schristley** [comment]
> The safest bet is probably to just copy Clone.repertoire_id unmodified from Rearrangement...

Yes, and those `x-airr` settings are correct, it should be non-miairr, required, nullable, and required for API. These settings should be on all identifiers in the schema, especially ones that link objects in the AIRR Data Model, while identifiers for non-AIRR objects can be optional.

**Comment by schristley** [comment]
> the generic jsonschema python package

We should try to move to something like this. My validation code is a simple recursive hack that's not very robust, it's also slow. However, it sounds like we'd have to modify the schema slightly before passing to the validator, at least for null. Might be worthwhile to see how OpenAPI V3 does against jsonschema, maybe transition to both at the same time.

**Comment by javh** [comment]
Okay, that sounds like consensus. I pushed the discussed changes. I also sync'd the `data_processing_id` x-airr tags and made minor changes to the `seed_id` description (please verify).

**Comment by eharkins** [comment]
FYI I've incorporated the AIRR Clones and Trees schema into Olmsted's input validation scripts. See https://github.com/matsengrp/olmsted/pull/146

**Comment by schristley** [comment]
@javh @eharkins This should be good to merge, right?

**Comment by javh** [comment]
Yeah, I think we can handle the x-airr tags, rearrangement_id and the count fields separately.

**Pull request merged**
