### PR TITLE
Minor fixes, and fix to the Sphinx build

### LINKED ISSUE #560: germline doc is missing from RTD
Even though the germline branch has been merged, the `latest` on RTD is not showing the documentation. Need to investigate.

### LINKED ISSUE #561: coding_sequence_identifier is missing from AlleleDescription
`coding_sequence_identifier` is in `required` but the field specification is missing under properties.

### PR DESCRIPTION
**Pull request by williamdlees**
Some minor changes to germline field names for consistency, and a fix to conf.py which should stop the Sphinx build breaking: names of some of the schema elements needed updating.

closes #561 
closes #560

### CODE REVIEW

**Comment by schristley** [comment]
Thanks @williamdlees , I see change for the sphinx doc builds, but are there supposed to be field name changes? I see a commit but maybe the changes were already in master?

**Comment by williamdlees** [comment]
You are right, they do seem to be there, though I can't see from the change history how they got there from this branch. Perhaps it was something to do with the way you fixed up the changes I over-wrote?

**Review by schristley — DISMISSED** [review]

**Comment by schristley** [comment]
needs more updates to `germline.rst`

**Comment by schristley** [comment]
@williamdlees I've added this branch to readthedocs so you can see the documentation changes.

I corrected the sentence, "In the case of a germline inference from a repertoire, ..." to refer to `RearrangementSequence` instead of `UnrearrangedSequence`. I think that is correct?

You may want to review the naming paragraph and add reference to you label generator tool. Also, the paragraph references `coding_sequence_identifier` but it isn't in the schema. I'd filed #561 about that, is that field missing or has it been changed?

**Comment by williamdlees** [comment]
Thanks @schristley . Sorry I forgot to update the documentation. You are correct about that reference to RearrangedSequence instead of UnrearrangedSequence. coding_sequence_identifier has now disappeared: the approach we're suggesting now is that label should be the IUIS name or a temporary label. I've reflected that in the documentation and added a link to IgLabel.

**Comment by williamdlees** [comment]
I think everything should be ok now.

**Review by schristley — APPROVED** [review]

**Review by bussec — COMMENTED** [review]
lgtm

**Pull request merged**
