### PR TITLE
Clone updates

### LINKED ISSUE #161: more documentation for duplicate_count
From a comment by Mathieu of vidjil group:

In particular, we used the `duplicate_count` key to describe the number of reads gathered in each clone, as you suggested us in your previous email. To enable a better interoperabilityn maybe this suggestion could be clearly stated in AIRR documentation of this field? For example, taking inspiration on what was already on the `sequence_id` field,  "duplicate_count (...) This may also be a total number of gathered sequences in cases where query sequences have been combined in some fashion by the tool."

### LINKED ISSUE #543: Clone spec mapping for common tools
Hello!

The iReceptor team is hoping to load some clones data, so we've been reviewing the clones [spec](https://github.com/airr-community/airr-standards/blob/3d78de34c887921836502f2256c0d57f9fb37876/specs/airr-schema.yaml#L2957).

I've created a mapping file with my best guess at mapping clones output from MiXCR, Change-o, 10X, and ImmuneDB. 

[clone.mapping_with_counts_examples-2021-10-29.xlsx](https://github.com/airr-community/airr-standards/files/7443603/clone.mapping_with_counts_examples-2021-10-29.xlsx)

Hoping for a review from the community to see if we are in agreement. Some specific questions that came out of this exercise:

1) It seems that most tools do not include v/d/j alignment start/end positions in the output. Am I missing something here - maybe a data processing step or a command-line argument?

2) For single-cell data, it became clear we'll need to resolve this issue: [extend clones to the single-cell context](https://github.com/airr-community/airr-standards/issues/317). Specifically for 10X data, clone_id comprises multiple loci, so we should decide if/how to split this out. We suggest modifying clone_id as follows (example is for BCR data): 

change clone_id = “CLONEA” to three clones with clone_id = “CLONEA_IGH”, clone_id = “CLONEA_IGL”, and clone_id = “CLONEA_IGK”.

3) In the same vein, we'll need to consider how to count clones derived from single-cell data. I came up with 3 options; option 1 (aggregating clone counts across loci) isn't very useful; option 2 (locus-specific clone count) makes more sense and can be implemented fairly easily; option 3 (cell-specific clone count) is most informative but might be trickier to implement right now, as it links to the cell spec. Any thoughts on how best to proceed?

Thanks!

### PR DESCRIPTION
**Pull request by bcorrie**
Closes #543 
Closes #161

### CODE REVIEW

**Comment by javh** [comment]
Thanks, @bcorrie. I pushed some updates for us to hammer on. I also added `umi_count` to Rearrangement and changes some of the wording in there.

One of the things we need to figure out is whether `clone_count` should be the count of:
1. Total sequences.
2. Unique sequence.
3. Either of the above, depending upon tool and analysis context.

I'm certain we talked about this before - I'll try to find where later.

**Comment by schristley** [comment]
I put the description for `clone_count` back to its original, which is to imply that the clonal assignment tool, or companion tool, decides what is the clonal abundance (count).

**Comment by javh** [comment]
@schristley, I don't think original description is correct. Two examples where this is plainly wrong are:

1. Classical bulk BCR sequencing clone sizes, which are often calculated as the number of unique variants.
2. Adaptive's data which does not provide non-normalized counts - only counts normalized to their standard curves.

**Comment by schristley** [comment]
> @schristley, I don't think the original description for `clone_count` is correct (which is why I changed it). Two examples where this is plainly wrong are:

@javh Okay, but your description makes it sound like it's just a count of rearrangement records. The original intent #471 of `clone_abundance` which got renamed to `clone_count` was to record what the analysis tool (and/or experimental protocol) inferred to be the clone size. "Non-normalized absolute" is meant to indicate that a frequency shouldn't be provided, as other analysis might want to perform their own normalization. Is this better?

Non-normalized absolute count of the _inferred_ number of members (immune cells) in this clone.

**Comment by javh** [comment]
"just a count of rearrangement records" will often be correct. Whether it's total sequences or unique sequences will depend upon whether duplicates were removed before calculating `clone_count`.

**Comment by javh** [comment]
@schristley, I like it. That seems to cover everything better than the original wording and my wording. We can probably drop the last sentence, as we don't need to provide suggestions for how to perform relative abundance calculations that aren't covered by a standard field.

**Comment by schristley** [comment]
We already starting making changes for #161 so we should make the other changes as well.

**Comment by scharch** [comment]
NOTE: This PR does **not** address #317

**Comment by bcorrie** [comment]
@javh there is a the Travis CI check that is not passing. Expected but waiting - is that expected?

**Comment by bcorrie** [comment]
Finally - synced all the specs so they pass consistency check 8-)

Hope I didn't screw up any definitions in the progress - @javh you are on for review, can you double check...

**Comment by javh** [comment]
Looks good to me. Thanks, @bcorrie. I'll merge this.

That weird Travis "expected but waiting" thing should be gone in every PR now.

Also, we need to get in touch with 10x about the `umi_count` field being in v1.4.

**Pull request merged**
