### PR TITLE
Add guidelines for annotation of 10X experiments

### LINKED ISSUE #417: How to represent PCR_target_locus from the 10X Genomics pipeline
I am trying to represent T cell data that has gone through the 10X/Cell Ranger pipeline in an AIRR compliant format. Their pipeline uses PCR amplification, so I want to assign a value to `pcr_target_locus`. The repertoires contain both TRA and TRB data so I was wondering, for the `pcr_target_locus` field, is there a way to show that the repertoire contains both in a succinct way? I was thinking something like "TRA, TRB" might work since it follows the controlled vocabulary but the examples suggest that there should only be one...

### PR DESCRIPTION
**Pull request by bussec**
Fixes #417

### CODE REVIEW

**Comment by bcorrie** [comment]
@kira-neller did you have any questions about pcr_target_locus descriptions for 10X studies... @schristley you are also looking at 10X data, correct, does this match what you are doing for pcr_target metadata for 10X studies?

**Comment by kira-neller** [comment]
Thanks @bcorrie. Yes, a couple questions - and please let me know if I should make separate issues for these. 

**1)** I was hoping to receive confirmation from @wyattmcdonnell on reverse_pcr_primer_target_location for: TRAC, TRBC, IGH, IGK, and IGL. 

Using the reverse inner primers (provided in Chromium Next GEM Single Cell V(D)J Reagent Kits v1.1 user guide ID CG000207 Rev E), I came up with TRAC (+42), TRBC (+52). Is this correct? Primers are: 
5’-AGTCTCTCAGCTGGTACACG-3’
5’-TCTGATGGCTCAAACACAGC-3’

For the IG loci, I am a bit confused because there are 7 primers, but only 3 loci to be annotated, I think (IGH, IGK, IGL). Clarification on this would be much appreciated. Primers are:
5’-GGGAAGTTTCTGGCGGTCA-3’
5’-GGTGGTACCCAGTTATCAAGCAT-3’
5’-GTGTCCCAGGTCACCATCAC-3’
5’-TCCTGAGGACTGTAGGACAGC-3’
5’-CACGCTGCTCGTATCCGA-3’
5’-TAGCTGCTGGCCGC-3’
5’-GCGTTATCCACCTTCCACTGT-3’

Will these reverse_pcr_primer_target_locations be the same for all 10X immune profiling kits (all chemistries/versions)?

**2)** Regarding # of cells used in the experiment, specifically fields cell_number and cells_per_reaction. If I understand correctly, cell_number is the approximate # of cells run through the 10X machine (e.g. 20,000). I'm not clear how this differs from cell_number ("number of cells for each biological replicate"). Through conversation with @bussec, cell_number should be 1. I also wonder if (and how) to document the actual number of cells analyzed for annotation (i.e. after all QC).    

I think it would be useful to include this information in the 10X guidelines.

Thank you!
Kira

**Comment by javh** [comment]
**1)** There are 5 constant regions for IGH, so these primers appear to be:

```
>IGHA
TGACCGCCAGAAACTTCCC
>IGHD
ATGCTTGATAACTGGGTACCACC
>IGHE
GTGATGGTGACCTGGGACAC
>IGHG
GCTGTCCTACAGTCCTCAGGA
>IGHM
TCGGATACGAGCAGCGTG
>IGLC
GCGGCCAGCAGCTA
>IGKC
ACAGTGGAAGGTGGATAACGC
```

(Reverse complement of the above).

IGLC genes have a lot of diversity, so you'll often see multiple IGLC primers as well, but that doesn't seem to be the case for the 10X primer set.

**Comment by kira-neller** [comment]
Thank you very much, @javh! 

So it looks like reverse_pcr_primer_target_locations are the following, plus the length of the respective primers: 
IGH: +142, +80, +114, +162, +54
IGK: +116
IGL:+192, +198, +229 

Is this correct?

**Comment by javh** [comment]
That looks right to me. Though, I think you can ignore the alignment against the IGLJ-C/OR18 ORF and pseudogene (the IGL +229).

**Comment by javh** [comment]
If you need the positions, here's the same for TR:

```
>TRAC
CGTGTACCAGCTGAGAGACT
>TRBC
GCTGTGTTTGAGCCATCAGA
```

[TRB.log](https://github.com/airr-community/airr-standards/files/5503195/TRB.log)
[TRA.log](https://github.com/airr-community/airr-standards/files/5503197/TRA.log)

**Comment by kira-neller** [comment]
Awesome, thanks so much. These positions agree with what I found, i.e. TRAC (+42), TRBC (+52), with the primer lengths included in these positions.

**Comment by bcorrie** [comment]
Well, that was all very nice - I don't think I understood any of it! 8-)

So my question is what of the above should go in the documentation guidelines??? And can someone make those changes, because I don't feel qualified!!!

**Comment by kira-neller** [comment]
Just to follow up on this - @bussec and/or @wyattmcdonnell could you please confirm if the positions above are correct for reverse_pcr_primer_target_locations for the 10X platform?

As well, apologies for the simplistic question, but I am not sure whether "most proximal nucleotide templated by the reverse primer" refers to the 5' or 3' end of the primer (i.e. whether the primer length is included in the position number). 

Thank you for clarifying!

**Comment by bcorrie** [comment]
I think @kira-neller had an outstanding question above that hasn't been answered... Unless it was answered elsewhere?

**Comment by kira-neller** [comment]
> I think @kira-neller had an outstanding question above that hasn't been answered... Unless it was answered elsewhere?

Yes, if I could get confirmation on the Nov 10/2020 question re: whether the primer length should be included in the position for primer_target_locations, that would be great. Thanks.

**Comment by bussec** [comment]
@kira-neller The terms *proximal* and *distal* refer to the start of respective V or C gene. 

Using *TRAC* and the TRAC primer (length: 20 nt) as an example

```
1   5    10   15   20   25   30   35   40   45   50   55  60   position (+1 = start of exon 1)
|...|....|....|....|....|....|....|....|....|....|....|....|
                      CGTGTACCAGCTGAGAGACT                     revcomp(TRAC primer)
ATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGACTCTAAATCCAGTGACAAGT   Chr. 14:22,547,506-22,547,565 (GRCh38)
                     ^*                  !                     markers
```

* +22 (marker `^`) is the most distal untemplated nucleotide
* +23 (marker `*`) is the most proximal templated nucleotide
* +42 (marker `!`) is the most distal templated nucleotide

So starting with your current positions, you would have to 1) substract the length of the primer and 2) add 1 to get to the position described in the spec.

The reasoning behind this is that typically primer-templated positions are less interesting, as they only tell us something about the primer, not about the template. Therefore we wanted to have a position that allows for simple trimming.

**Comment by kira-neller** [comment]
Thanks @bussec! Makes sense to me.

**Pull request merged**
