### PR TITLE
restructure schema

### LINKED ISSUE #53: There are two of each object in definitions.yaml
Is it possible to deduplicate the objects in definitions.yaml?  Is this a temporary situation?

### PR DESCRIPTION
**Pull request by schristley**
fixes #53 
also #67

### CODE REVIEW

**Comment by schristley** [comment]
@bcorrie, you can see the new structure.

**Comment by laserson** [comment]
@schristley I squashed and rebased the changes onto the latest master. I saw a bunch of `x-mairr` fields, but I'm assuming you meant `x-miairr`? I added an extra commit making these changes. I'll squash it in if you agree.

**Comment by bcorrie** [comment]
@schristley - your changes seem to make sense... Have you been able to test them in the iReceptor API in any way? What we should probably do is merge the AIRR Compliance branch of the iReceptor API into master (as it is what we are using now), tag it as a release when we release iReceptor v2.0 next month, and then use the new defintions.yaml version that you have now on a new branch to ensure it doesn't break anything on the OpenAPI/Swagger interface of our APIs.

Let me know if you have been able to test the new definitions.yaml with the iReceptor API and your VDJServer... I suspect not...

Brian

**Comment by schristley** [comment]
@bcorrie No I haven't tested yet in iReceptor, I intended too but didn't get to it yet. And, yeah, I kinda wanted to touch base with you about the AIRR Compliance branch. I didn't necessary want to update it until I checked with you.

Do you want to tag the AIRR Compliance branch with some "Dec demo" tag, so we know exactly what was used for the AIRR meeting? Are you wanting to keep the AIRR Compliance branch, maybe we should merge it, tag it, and get development back to the normal branches?

**Pull request merged**
