### PR TITLE
Change and document MiAIRR requirement levels

### LINKED ISSUE #204: Synthetic antibodies and MiAIRR
@bussec and I have been having a discussion with a colleague around synthetic antibiody data and which fields would be nullable (related to #96). I wanted to capture this in an AIRR issue rather than in the email thread. I think the nullable part has been agreed, it is more around the definition and examples where discussion is ongoing.

Currently, the fields being discussed (and in particular their meaning for synthetic antibody data) are: 
    synthetic:
    organism:
    sample_type:
    single_cell:
    cell_storage:
    template_class:
    library_generation_method:
    complete_sequences:
    physical_linkage:

Other than some example clarification, the current fields where discussion is ongoing are:
    sample_type
    physical linkage

@bussec I think that is where our email conversation had ended, correct me if I am wrong, and if you think you have closure on this then you can close the issue. I thought there were a couple of outstanding thinks on the last two that still needed clarification?

### LINKED ISSUE #310: Revisit MiAIRR non-nullable fields
Creating this issue to replace the specific issue around cell_storage in #307 (which I will close).

In the current spec the following are required and non-nullable. Note ```sample_type```, ```tissue```, and ```single_cell```  are missing from the original list in #96

Are these still the "correct" fields to be required and non-nullable?

```
        synthetic:
            type: boolean
            description: TRUE for libraries in which the diversity has been synthetically generated (e.g. phage display)
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        organism:
            $ref: '#/Ontology'
            description: Binomial designation of subject's species
            example:
                id: 9096
                value: Homo sapiens
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        cell_storage:
            type: boolean
            description: TRUE if cells were cryo-preserved between isolation and further processing
            example: TRUE
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        template_class:
            type: string
            enum:
                - DNA
                - RNA
            description: The class of nucleic acid that was used as primary starting material for the following procedures
            example: RNA
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        library_generation_method:
            type: string
            enum:
                - "PCR"
                - "RT(RHP)+PCR"
                - "RT(oligo-dT)+PCR"
                - "RT(oligo-dT)+TS+PCR"
                - "RT(oligo-dT)+TS(UMI)+PCR"
                - "RT(specific)+PCR"
                - "RT(specific)+TS+PCR"
                - "RT(specific)+TS(UMI)+PCR"
                - "RT(specific+UMI)+PCR"
                - "RT(specific+UMI)+TS+PCR"
                - "RT(specific)+TS"
                - "other"
            description: Generic type of library generation
            example: RT(oligo-dT)+TS(UMI)+PCR
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        complete_sequences:
            type: string
            enum:
                - partial
                - complete
                - "complete+untemplated"
            description: >
                To be considered `complete`, the procedure used for library construction MUST generate sequences that
                1) include the first V segment codon that encodes the mature polypeptide chain (i.e. after the
                leader sequence) and 2) include the last complete codon of the J segment (i.e. 1 bp 5' of the J->C
                splice site) and 3) provide sequence information for all positions between 1) and 2). To be considered
                `complete & untemplated`, the sections of the sequences defined in points 1) to 3) of the previous
                sentence MUST be untemplated, i.e. MUST NOT overlap with the primers used in library preparation.
            example: partial
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        physical_linkage:
            type: string
            enum:
                - none
                - "hetero_head-head"
            description: >
                Describes the mode of linkage if a method was used which physically links nucleic acids derived from
                distinct loci in a single-cell context.
            example: hetero_head-head
            x-airr:
                miairr: true
                required: true
                nullable: false
```

### PR DESCRIPTION
**Pull request by bussec**
* Change various requirement level to provide for easier annotation by third-party annotators.
* Add documentation for requirement levels.
* Add guideline for annotation of synthetic libraries
* Expand controlled vocabulary for `physical_linkage`

Fixes #310 
Fixes #204

### CODE REVIEW

**Comment by schristley** [comment]
@bussec I feel like maybe the documentation should be put under `datarep/overview.html` instead of MiAIRR? Though I get the point that the PR is really to document the MiAIRR levels, but it makes me wonder if we generalize that presentation, then we can also document requirements for the AIRR file formats and ADC API. We can share/link/duplicate the information across the pages if that's helpful.

I like the guidelines page, that's a place where we can document odds and ends like #219 , #242 , etc. The file mentioned in #219 doesn't seem to be linked into the docs.

**Comment by bussec** [comment]
@schristley I now moved the the documentation to `datarep`. Are you ok with merging and opening up PRs to deal with #219 and #242 ?

**Comment by schristley** [comment]
Thanks @bussec. It looks good.

@javh @bcorrie Have we resolved how to handle `required` across use cases (.e.g AIRR TSV, ADC API, whatever else)? Are we going combine these so that `required` is encompassing all use cases, or are we going to implement additional flags to indicate `required` under different circumstances?

Personally, I'd prefer to just have a single `required` that encompasses all. I realize this is going to increase the size of AIRR TSV files, but the advantage is it is simpler.

**Comment by javh** [comment]
No, I don't think we've sorted that out yet. I made a new comment in #297 with another suggestion.

**Comment by bcorrie** [comment]
> No, I don't think we've sorted that out yet. I made a new comment in #297 with another suggestion.

I was at a conference all week so I am a bit (a lot) behind. I just made a bunch of comments on the required discussion...

**Comment by bcorrie** [comment]
Had a look - looks good... Once we sort out the #297

**Comment by schristley** [comment]
When #297 is sorted out, will use this branch to update the schema and validation routines.

**Comment by bussec** [comment]
@schristley  @bcorrie please review:
* I now updated the docs to reflect the changes in requirement levels and the `required` tag introduced in #342.
* Will open a new branch to address #219.
* Would like to wait with #242 until the end of the next OntoVoc sprint.

**Comment by bussec** [comment]
Resolved merge conflicts manually.

**Pull request closed without merging**
