### PR TITLE
Introduce Receptor schema

### LINKED ISSUE #44: epitope and specificity information
This is an issue that Bjoern brought up on the CRWG mailing list, whether part of MiAIRR or just support in formats is worth discussion.

> The alternative is to describe the exact epitope recognized as part of the MIARR standard. That is absolutely possible, but will require a substantial update -  I thought the point of using the IEDB record was that this takes away that complexity. If the epitope should be described, minimally you will need 
> - epitope type (linear peptide, discontinuous amino acids, non-peptidic)
> - epitope molecular structure (3 different fields, depending on type above)
> - epitope source protein
> - epitope source organism
> 
> There are a bunch of additional fields (e.g. is this the exact epitope / an epitope containing region / a partial epitope). But as a start you might want to err on the minimal info above. 

> The primary use case at that point was that people are using e.g. MHC tetramer staining to isolate epitope specific repertoires.

### LINKED ISSUE #207: Single-cell reactivity data annotation/linkage
For general background, see #206. The aim is to provide reactivity information for individual Ig/TCRs. Although this will often occur in a single-cell context, attaching the information to the `paired_chain_id` (and not to `cell_id`) is important as individual cells can express multiple receptors, e.g. due to simultaneous expression of two TCR alpha chains. Referencing to the reactivity record via `paired_chain_id` resolves this issue and at the same time allow the annotation of stochastically inferred chain pairs, which inherently lack a `cell_id`.

The proposal is to add the following record structure to the AIRR schema, so that it can be referenced by the paired-chain identifier.

* single-cell reactivity data:
  * keyword describing the methodology used for measurement. Note that only methods that return an absolute and quantitative measurement can be used (affinity, binding energy, etc.). Examples: "SPR", "ITC".
  * UID of the receptor at IEDB, which can hold additional and richer data records.
  * DOI of raw data measurements
  * _n_ records of reactivity measurement
    * `antigen`: The antigen against which the receptor was tested. For TCRs this is the combination of MHC and peptide.
    * `value`: The absolute (processed) value of the measurement.
    * `unit`: The physical unit of the measurement, e.g. M or kJ mol-1

Potential issues:
* `antigen`: To allow meaningful comparisons across studies, this field must be populated from a controlled vocabulary, IEDB would be the obvious candidate for this, but need to check whether there are any potential restrictions in terms of molecule classes.

### LINKED ISSUE #293: Representation of bispecific antibodies
This was briefly mentioned by @javh in yesterday's DataRep call:

How can we represent immunoglobulins that consist of more than one heavy and one light chain species. Our current concept of `paired_id` assumes that we combine two chains into a single Ig.

This would most likely happen in things like bispecific constructs, but it could also apply to immunoglobulins produced by B cells with two productive light chains (although it is harder the verify the actual existence of the latter one).

### LINKED ISSUE #410: Receptor, Cell and Rearrangement schema representations
**Receptor**

A receptor represents two chains(i.e. one heavy and one light) of a cell, each with a antigen-binding site. However, an individual cells can also express multiple receptors, e.g. due to simultaneous expression of two TCR alpha chains. 

Aim of the ```Receptor``` object is to provide reactivity information for individual Ig/TCRs. 
```Receptor``` object which is currently available in the pull request #404. 

However, if the amino acid sequences of V-region of both receptor chains are identical and grouping them together will be considered as identical receptors and they would have identical reactivity information. So, the question was how to represent them in order to avoid redundancy of identical ```Receptor``` object?

**Relationship between Receptor, Cell and Rearrangement**

The current schema for ```Cell```, ```Rearrangement ```and ```Receptor``` is represented below  

• ```Receptor``` has N: N with ```Cell``` – A cell would contain multiple receptors and a receptor can be from multiple cells

• ```Receptor``` has 1:2 with ```Rearrangement``` –Two rearrangement represents a receptor and a receptor contains only two rearrangements sequences.

However the current linkage between ```Receptor``` and ```Rearrangement``` breaks because the rearranged sequences associated with the receptor might be different as receptors are determined at amino acid level whereas rearranged sequences are determined at nucleotide level there by having any synonymous substitution would lead to identical V-region of both receptor chains but their rearrangements would not be identical. Hence, 2:1 ```Rearrangement```:```Receptor``` does not hold true.

Given the schema representations that allows N:N Cell:Receptor relationship we have come up with two schema proposals and would be good to get some suggestions/comments on the proposed schemas below. 

**Proposal 1:**

In the proposed schema we define two ```Receptor``` objects i.e ```Intermediate``` and ```Observed Receptor``` where multiple ```Intermediate Receptor``` objects are related to a single ```Cell ``` object and a ```Observed Receptor``` object is linked to multiple ```Intermediate Receptor``` object and there are no direct linkage to ```Cell``` Object.  

The ```Observed Receptor``` object will then contain same properties as what we have defined currently in #409 but with addition of amino acid sequences of the receptor chains.

**Proposal 2:**

• ```Receptor``` has N:1 with ```Cell``` – A cell would contain multiple receptors and a receptor can be present in single cell

Here we then do not link``` Receptor``` to ```Rearrangement``` but as proposed for ```Observed Receptor``` we should extend the current```Receptor``` object by addition of the protein sequences of both receptor chains

### LINKED ISSUE #540: IDs for Receptor objects
_Originally posted by @schristley in https://github.com/airr-community/airr-standards/issues/524#issuecomment-868818350_

IEDB has [released](https://help.iedb.org/hc/en-us/articles/4402872882189-Immune-Epitope-Database-Query-API-IQ-API-) a beta query API for their database.

Of interest is they have a [curie_map endpoint](https://query-api.iedb.org/curie_map) which returns a structure similar to our `CURIEMap`. I've noticed however that the IRI goes to the human-readable html page instead of the API which returns machine-readable JSON. For example, `IEDB_EPITOPE: 7355` resolves to:

```
https://www.iedb.org/epitope/7355
```

versus

```
https://query-api.iedb.org/epitope_search?structure_id=eq.7355
```

The nice thing is that now we should be to add a single field in Rearrangement if we want to link to an epitope #44 

Though that opens the question on whether we should put entries into our CURIEMap for resolving `IEDB_EPITOPE` or if we should use IEDB's?

We also can consider how we might link with receptors. The IEDB API has `tcr_search` and `bcr_search` endpoints:

```
https://query-api.iedb.org/tcr_search?limit=5
https://query-api.iedb.org/bcr_search?limit=5
```

The receptor ids have `IEDB_RECEPTOR` as their CURIE though oddly it's missing from the above curie_map. However, we might want to consider how we can link our `Receptor` to IEDB's.

### PR DESCRIPTION
**Pull request by sharikrish**
Fixes #44
Fixes #207
Fixes #293
Fixes #410
Fixes #540

### CODE REVIEW

**Comment by scharch** [comment]
In addition to adding the amino acid sequences to `Receptor` (per #409), I think you will want to identify which is the heavy/beta/delta and which is the lambda/kappa/alpha/gamma. Relatedly, it might be useful to have a top-level property that defines what type of `Receptor` this is.

For BCRs, is isotype a property of the `Receptor` or of the `Cell`? I lean toward the latter, since it doesn't affect antigen binding (and the same `Receptor` could be observed in multiple isotypes), but if the use case is synthesizing a `Receptor` of interest, it might be useful to have that information there...

**Comment by bcorrie** [comment]
All, should we be adding a /cell and /receptor ADC API entry point as part of this schema change? This seems logical to me. I can make the changes if you give me the thumbs up, since I recently did this for /clone...

**Comment by bcorrie** [comment]
I have created #466 as a pull request to integrate the /cell API endpoint. There is no /receptor endpoint as of yet.

**Comment by bcorrie** [comment]
> I have created #466 as a pull request to integrate the /cell API endpoint. There is no /receptor endpoint as of yet.

@bussec @sharikrish @schristley do you want to review? From the API perspective, it is relatively trivial to add the endpoint. This assumes that the `Cell` object data is what the API will return.

**Comment by bussec** [comment]
@bcorrie I moved the `Cell` related changes in this PR to #466 now. Unless there is any reason to implement `/cell` and `/receptor` simultaneously that (i.e. 466) should be good to go.

**Comment by bussec** [comment]
Rebasing to avoid conflicts in `schema.yaml`...

**Comment by schristley** [comment]
With IEDB's new query API, we can consider how we might link our `Receptor` with IEDB's. Some additional information is in the [OntoVoc comment](https://github.com/airr-community/airr-standards/pull/524#issuecomment-868818350).

**Comment by bcorrie** [comment]
Couple of minor comments:

- Me thinks `reactivity_unit` should be a UO Ontology field???
- It would be nice if the receptor_gid would follow the same GID protocol (yet to be defined) of other GIDs - although your GID generation is kinda cool 8-)

**Comment by bussec** [comment]
@bcorrie 

> It would be nice if the receptor_gid would follow the same GID protocol (yet to be defined) of other GIDs - although your GID generation is kinda cool 8-)

We can replace the `_gid` field with something like a UUID and rename the current fields to `_hash`. But I think it is important to  have this functionality (ids that are identical across repositories).

**Comment by bussec** [comment]
@bcorrie @scharch @schristley This is now feature-complete from our side, please have a look.

**Comment by bcorrie** [comment]
I don't have any objections to adding this to the v1.4 spec - as long as you science-y types are OK with the definitions etc. 8-)

In addition, if we have this object defined in the v1.4 spec, I would suggest we add it as an API endpoint in ADC V1.2 release (as discussed in #579) @schristley any objections to me adding this to the ADC API YAML spec? Repositories would need to implement, but they just return no data if they don't store Receptor object in their repository...

**Comment by scharch** [comment]
Naive question: what does 
`$ref: '#/Ontology'`
mean?

Otherwise, I think it looks fine.

**Comment by bussec** [comment]
@scharch 

> what does $ref: '#/Ontology' mean?

Basically, this is an `include` statement that copies the `Ontology` object (line 18ff. of the schema) into the position of the `$ref`. See [here](https://swagger.io/docs/specification/using-ref/) for details.

**Comment by bussec** [comment]
> In addition, if we have this object defined in the v1.4 spec, I would suggest we add it as an API endpoint in ADC V1.2 release (as discussed in https://github.com/airr-community/airr-standards/issues/579)

Has now been added in [fcdfdd3](https://github.com/airr-community/airr-standards/pull/404/commits/fcdfdd3360f5adcdf22138fefc1abfe05b438487).

**Review by bcorrie — APPROVED** [review]

**Pull request merged**
