### PR TITLE
Refactor documentation table generation

### LINKED ISSUE #390: Inconsistency between Rearrangement and metadata field tables in docs
Sorry I didn't catch this earlier, but the field tables aren't consistent across the Rearrangement, metadata (Repertoire), and experimental schema (Alignment, Clone, Tree, Node, Cell).

Rearrangement and Alignment have columns:  Name, Type, Priority, Description. I changed "Priority" to "Level" in #389. Where Level is either `required` (in top level `required`) or `optional` (not in top level `required`). 

Metadata objects and Clone, Tree, Node and Cell have "MiAIRR" instead of "Level".

The former also have a **Download as TSV** link and the latter do not.

I think these should be consistent. At the very least Clone, Tree, Node and Cell should follow whatever rules we use for Rearrangement and Alignment. I can see an argument for making the metadata field tables different. Though, I'm not certain "MiAIRR" is the right terminology to the convey the requirement levels. We can populated the column from the `x-miairr` tag, but I don't think the distinction between MiAIRR and not-MiAIRR is very useful.

Thoughts? I'm guessing this is partly due to us having some redundant code in `docs/conf.py` for building tables.

### PR DESCRIPTION
**Pull request by javh**
Resolves #390, #393 and #397.

I've tried to merge all table generating code for the docs into a single approach. Previously, there were separate code chunks for the Rearrangement/Alignment tables, metadata tables, and MiAIRR tables.

They didn't all work the same, so I tried to compromise where the implementations differed. Not sure if I got the ontology stuff correct, in particular.

### CODE REVIEW

**Comment by javh** [comment]
I enabled building of this branch on RTD temporarily:
https://docs.airr-community.org/en/docs-tables/

**Comment by bussec** [comment]
Thanks @javh ! The ontology stuff looks ok, we will need to see whether it breaks if we merge #385. There is still an issue with the `cell` object at the bottom of the table, we'll look into this tomorrow.

**Comment by javh** [comment]
Sounds good. Oh, I forgot to mention, I cut the MiAIRR table off at Set 5 - I wasn't sure which specs, if any, from Set 6 should be in that table.

**Comment by javh** [comment]
Okay, so can we merge in #385 first, then update this branch with @franasa's fixes?

**Comment by schristley** [comment]
The ontology link isn't showing in the fields tables, e.g. `study_type` has a type of `string` when it should be `Ontology`

**Comment by bussec** [comment]
@schristley Are we talking about the same table? Because [here](https://docs.airr-community.org/en/docs-tables/miairr/data_elements.html) the ontology is present (the same is true for the `master` [branch tip of the doc](https://docs.airr-community.org/en/latest/miairr/data_elements.html))...

**Comment by schristley** [comment]
nope, talking about these [tables](https://docs.airr-community.org/en/docs-tables/datarep/metadata.html). Somehow, the deprecated `organism` field still has the ontology link but not the other fields.

**Comment by javh** [comment]
I think this is one of those cases where the MiAIRR table and the metadata schema tables didn't use the same format for the "Type" column.

E.g., the MiAIRR table `study_type` is:

**Type:** string
**Format:** Ontology: { name: NCIT , top_node: { id: C63536, value: Study}, draft: True}

Metadata schema tables `study_type` is:

**Type:** [Ontology](https://docs.airr-community.org/en/docs-tables/ontovoc/introduction_ontovoc.html#ontovoc)

**Comment by schristley** [comment]
I think the metadata tables need to say `Ontology` with link to ontology page, because having the type listed as `string` is confusing and not correct as the actual type is an `object`.

**Comment by bussec** [comment]
> I picked the MiAIRR format. Not sure if that's ideal. What's the preference?

Linking to the Ontovoc table has probably a better readability, so I agree with @schristley. We could refer to the individual ontologies via `#fragment` in the URL if necessary.

**Comment by javh** [comment]
I made the change to the Ontology type, minus the `#fragment` bit.

**Comment by bussec** [comment]
So we merge #385 now and finalize this tomorrow?

**Comment by javh** [comment]
Works for me.

**Pull request merged**
