### PR TITLE
Merge info response fix into master

### PR DESCRIPTION
**Pull request by bcorrie**

### CODE REVIEW

**Comment by schristley** [comment]
@bcorrie I'm pretty sure these changes have already been merged in? This pull request will create two [service_info_object](https://github.com/airr-community/airr-standards/blob/eb03fe05d1ebf80ba58aeddc61f9f2a216cf410d/specs/adc-api.yaml) which we don't want.

**Comment by bcorrie** [comment]
> @bcorrie I'm pretty sure these changes have already been merged in? This pull request will create two [service_info_object](https://github.com/airr-community/airr-standards/blob/eb03fe05d1ebf80ba58aeddc61f9f2a216cf410d/specs/adc-api.yaml) which we don't want.

I am trying to clean up stray branches and make sure we get everything in the v1.3 release that we need... According to the branch flow this has not been merged in so those changes must have been duplicated in another branch...

**Comment by schristley** [comment]
> I am trying to clean up stray branches and make sure we get everything in the v1.3 release that we need... According to the branch flow this has not been merged in so those changes must have been duplicated in another branch...

Ok, I see. Regardless, don't merge this as is because it will create a duplicate service_info_object. The /info changes were merged in #375

**Comment by bcorrie** [comment]
See my comment here: https://github.com/airr-community/airr-standards/pull/399#issuecomment-631624999

It appears that our rebase/merge into master approach is confusing - at least to me... It isn't really possible for me to see if these changes were made or not, but it looks like they were rebased into master (although I can't find an indication of that anywhere?)

What am I missing?

**Pull request closed without merging**
