### PR TITLE
Added content type to curl post queries

### LINKED ISSUE #576: ADC curl POST commands in docs need a header
Some repositories (at least VDJServer) are strict and require the header to be of the correct type. The documentation doesn't say this and the curl commands don't work against VDJServer. This doesn't work:

curl --data @/data/src/AIRR/adc-api-tests/repertoire/pass-query1-2_repertoire.json https://vdjserver.org/airr/v1/repertoire

While this does:

curl -H "Content-Type: application/json" --data @/data/src/AIRR/adc-api-tests/repertoire/pass-query1-2_repertoire.json https://vdjserver.org/airr/v1/repertoire

### PR DESCRIPTION
**Pull request by bcorrie**
-H "Content-Type: application/json"

Closes #576

### CODE REVIEW

**Comment by bcorrie** [comment]
@schristley I think this is ready to merge/close with the exception of the VDJServer examples having hardcoded IDs

**Comment by schristley** [comment]
@bcorrie I believe these changes are included in #601

**Comment by javh** [comment]
Can we void this one then?

**Comment by bcorrie** [comment]
It looks like it - the header changes are in #601 as well. I am closing...

**Pull request closed without merging**
